from common import P, S, R, char_scenes
NECK = char_scenes("dongmin", "mija", "deoksu", "bonggu", "yeongran", "gyeongho", "gyeongmin", "suni", "seoki", outfit="빨간 손수건")
NECK = sorted(set(NECK), key=lambda s: (int(s.split("-")[0]), int(s.split("-")[1])))

TIN, RUST, SPOON, FORK = "#B9BDBF", "#8E4B2A", "#C9A06A", "#A7ACB0"

DONG_SHAPE = ("a large cylindrical milk-powder tin can with its paper label removed, laid on its side lengthwise as the body "
              "(15cm diameter, 17cm long), a long wooden cooking spoon pushed into a hole just under the top edge of the front end "
              "of the can so the flat spoon handle runs level with the top of the can as the neck (26cm of handle outside the can), "
              "the oval spoon bowl at the far end serves as the head with four small wooden pegs, two through each side of the bowl rim, "
              "a stainless table fork bent into an L standing on the top of the can as the bridge: its four tines point straight up, "
              "one string resting in each tine tip, its handle folded flat along the can, "
              "four real violin strings running from the pegs along the spoon handle over the fork tines to a twisted iron wire loop "
              "wrapped around the rear rim of the can, no sound holes, an old real violin bow shown beside it")
DONG_MAT = "tinplate can, pale wooden spoon, stainless steel fork, steel violin strings, iron wire"
DONG_SIZE = "about 52cm long overall, can 15cm diameter by 17cm, spoon 45cm, bow 74cm"
DONG_COND = "bare tin with a faint pale glue band where the label was peeled off, a ring of rust about 1cm wide on both rims, small scratches, the spoon wood clean and pale"

A = [
P("dongguri", "동그리(깡통 바이올린 1호)", "A",
  R("1-11", "1-13", "1-14", "2-1..2-4", "2-10", "2-13", "2-14", "2-17", "2-18", "2-22", "2-23", "2-27", "2-28",
    "3-1..3-3", "3-6..3-10", "3-15", "3-17..3-22", "3-24..3-30", "3-34"),
  aliases=["동그리", "깡통 바이올린 1호", "분유 깡통 바이올린", "은주의 깡통 바이올린"],
  era="1987~88 서울(에필로그 2003)",
  material="양철(석도강판) 큰 분유 깡통(상표 종이 벗김), 나무 숟가락(목), 스테인리스 식탁 포크(줄받침), 진짜 바이올린 줄 4개(곽 영감 공장 시절 남은 것), 나무못 4, 쇠철사(꼬리 고리)",
  size="전체 길이 약 52cm. 깡통 지름 15cm·길이 17cm(눕혀 씀), 나무 숟가락 45cm(깡통 밖 목 26cm, 머리 9×6cm), 포크 줄받침 높이 3.5cm, 활 74cm",
  colors=[TIN, RUST, SPOON, FORK],
  condition="상표 종이를 벗긴 맨 양철. 종이가 붙어 있던 자리에 옅은 풀 자국 띠. 앞뒤 테두리(이음매)에 폭 1cm 녹 띠(대본 '녹슨 테두리'). 잔긁힘. 숟가락은 처음엔 밝은 생나무색",
  shape="깡통을 옆으로 눕혀 몸통으로 쓴다(깡통 축이 줄 방향). 앞쪽 원판 윗가장자리 바로 아래 구멍에 나무 숟가락 자루를 꽂아, 자루 윗면이 깡통 윗선과 수평으로 이어지게 한다(지판 겸 목). "
        "숟가락 둥근 머리가 악기 머리가 되고, 머리 가장자리 양옆에 나무못 2개씩(모두 4개). 포크는 목 부분을 ㄱ자로 꺾어 날 4개가 위로 서게 깡통 윗면에 세운다(줄받침) — 날 끝 하나에 줄 하나씩. "
        "포크 자루는 깡통 윗면을 따라 뒤로 눕힌다. 줄 4개는 나무못 → 숟가락 자루 위 → 포크 날 → 깡통 뒤 테두리에 두 번 감은 철사 고리에 건다. 울림구멍 없음. 턱은 깡통 뒤 테두리에 댄다",
  role="주인공의 악기이자 작품의 상징. 은주가 처음 '갖고 싶다'고 말한 소리(1-11). 아버지가 던짐(2-10) → 미자·덕수·곽 영감이 되찾음 → 은주가 작은 산에 버림(2-23) → 아버지가 찾아 곽 영감에게(2-27~28) → 본선 E현 끊김과 교체(3-21~24) → 15년 뒤에도 연주(3-34)",
  ref="형태 참고만: https://en.wikipedia.org/wiki/Recycled_Orchestra_of_Cateura (깡통·숟가락·포크), https://commons.wikimedia.org/wiki/File:Instruments_made_from_recycled_metal_(14350937984).jpg. 한국 분유통 치수·깡통 방향·숟가락 머리 줄감개·꼬리 철사는 디자인 판단(미확인)",
  en=dict(name="'Donggeuri', a homemade violin made from a milk-powder tin can", shape=DONG_SHAPE, material=DONG_MAT,
          size=DONG_SIZE, condition=DONG_COND),
  offscreen="2-24(대사로만 언급)",
  notes="악기 재료는 continuity.md 악기 표·대본 Insert 그대로(큰 분유 깡통 몸통, 나무 숟가락 목, 구부린 포크 줄받침, 진짜 바이올린 줄 4, 나무못). 포크는 줄받침(카테우라의 줄걸이와 다름). 깡통 방향·줄감개·꼬리 철사·울림구멍 없음은 디자인 판단",
  states=[
    S("dongguri__s1_first", "처음(곽 영감이 만든 그대로)", R("1-11", "1-13", "1-14", "2-1..2-4", "2-10"),
      "1-11 천에 싸여 옴(싼 천은 wrap_cloth). 녹슨 테두리, 밝은 생나무 숟가락, 은빛 포크, 줄 4개 팽팽. 연습하며 손자국만 늘어남"),
    S("dongguri__s2_thrown", "던져짐 — 포크 줄받침 꺾임", ["2-10"],
      "쓰레기 더미에 부딪혀 포크 줄받침이 꺾여 눕고 줄 4개가 깡통 위로 느슨히 처짐. 빗물·진흙 튐. 깡통은 찌그러지지 않음('깡통은 멀쩡하다' 2-13). 화면엔 소리(딱)만 — 콘티 인서트가 필요할 때 씀",
      shape=DONG_SHAPE.replace("standing on the top of the can as the bridge: its four tines point straight up, one string resting in each tine tip, its handle folded flat along the can",
                               "that served as the bridge now snapped over at its bend and lying flat on the can, the four strings slack and sagging onto the can").replace(", an old real violin bow shown beside it", ""),
      condition="wet with rain, splashed with brown mud, the can itself undented, rust ring on both rims"),
    S("dongguri__s3_fork_replaced", "포크만 갈아 끼움(곽 영감 수리)", R("2-13", "2-14", "2-17", "2-18", "2-22"),
      "진흙을 말끔히 닦음. 줄받침 자리에 새 포크를 구부려 박음 — 새 포크가 전보다 조금 더 반짝(#C9CED2). 깡통·숟가락·줄은 그대로. 2-14·2-22 공방 선반에서 천을 덮고 누움",
      condition="mud wiped clean, the newly bent replacement fork slightly shinier than the rest, the same old strings, rust ring on both rims",
      colors=[TIN, RUST, SPOON, "#C9CED2"]),
    S("dongguri__s4_abandoned", "버려짐 — 줄 풀림(작은 산 판자 위)", R("2-23", "2-27", "2-28"),
      "은주가 나무못을 하나씩 풀어 줄 4개가 힘없이 늘어짐(줄은 떼지 않음). 납작한 판자 위에 눕힘. 2-27 밤이슬이 몸통에 맺히고 숟가락 목이 젖어 거뭇함(#8A6A45). 2-28 만석이 품에서 꺼내 내밂",
      shape=DONG_SHAPE.replace("four real violin strings running", "four real violin strings, pegs loosened so the strings hang slack in loose curves, running").replace(", an old real violin bow shown beside it", ""),
      condition="beads of night dew on the tin, the spoon neck darkened by moisture, rust ring on both rims",
      colors=[TIN, RUST, "#8A6A45", "#C9CED2"]),
    S("dongguri__s5_restored", "다시 손봄(곽 영감·만석의 사흘 밤)", R("3-1..3-3", "3-6..3-10", "3-15", "3-17"),
      "몸통을 반들반들 닦음. 나무 숟가락 목 이음매에 새 아교 자국이 호박색으로 반짝(#D9A441). 줄은 공장 시절 그 4개를 다시 고른 것(새 줄 아님 — '새로 고른 듯' 팽팽). 2-13의 새 포크 그대로",
      condition="the tin polished to a soft shine, a fresh glossy amber line of hide glue around the neck joint, the original four strings retuned taut, rust ring on both rims",
      colors=[TIN, RUST, SPOON, "#D9A441"]),
    S("dongguri__s6_worn_e", "본선 — E현이 닳음", R("3-18..3-20"),
      "s5와 같고, 1번 줄(E현, 가장 가는 줄)의 손가락 짚는 자리 3~8cm가 닳아 빛이 바램(무광 회색 #8C9196). 3-18 태준 '…E현이 많이 닳았네' 극접사",
      condition="polished tin, amber glue line at the neck joint, the thinnest string (E) dull gray and worn along the fingering area, the other three strings normal",
      colors=[TIN, RUST, SPOON, "#8C9196"]),
    S("dongguri__s7_e_broken", "본선 — E현 끊김", R("3-21", "3-22"),
      "'저녁' 독주 중 E현이 끊어져 은주 손을 비껴 동그르르 말려 올라감. 끊어진 끝이 작은 고리 몇 겹으로 말림. 나머지 3줄은 그대로. 3-22 곽 영감이 끊어진 줄을 풀어냄",
      shape=DONG_SHAPE.replace("four real violin strings running", "four real violin strings, the thinnest one (E) snapped with its loose end curled into small springy coils, running").replace(", an old real violin bow shown beside it", ""),
      condition="polished tin, amber glue line at the neck joint, one snapped string curling in the air"),
    S("dongguri__s8_new_e", "본선 — 태준의 새 E현으로 교체", R("3-24..3-30"),
      "곽 영감이 무대 옆에서 1분 안에 태준의 여분 E현을 포크 줄받침 위로 넘겨 나무못에 감음. 새 E현만 혼자 은빛으로 반짝(#E4E8EC), 나머지 3줄은 옛 줄",
      condition="polished tin, amber glue line at the neck joint, one brand-new bright silver E string that shines alone beside three older duller strings",
      colors=[TIN, RUST, SPOON, "#E4E8EC"]),
    S("dongguri__s9_epilogue", "15년 뒤(2003 봄, 에필로그)", ["3-34"],
      "몸통 여기저기 찌그러짐(오목한 자국 4~5곳), 나무 숟가락 목은 손때로 까맘(#3B2A1E). 녹 띠가 더 짙어짐. 줄 상태는 대본에 없음 — 단정하지 않음(4줄이 걸려 있다는 것만)",
      condition="the tin dented in four or five places, the wooden spoon neck darkened almost black by years of hand grime, a deeper rust ring on both rims, still carefully kept",
      colors=[TIN, "#6E3A22", "#3B2A1E", FORK], era="2003 Seoul"),
  ]),

P("ttungbo", "뚱보(기름통 첼로)", "A",
  R("1-12", "1-14", "2-1..2-4", "2-6", "2-10", "2-14", "2-18", "3-5", "3-6", "3-9", "3-10", "3-18..3-21", "3-23", "3-25", "3-27"),
  aliases=["뚱보", "기름통 첼로", "기름통"],
  material="철제 기름통(드럼통)을 가로로 반 잘라 낸 아랫동, 각목 목(소나무), 2-1 이후 피아노 쇠줄 4개, 나무토막 줄받침, 나무못 4",
  size="높이 140cm(은주 키와 같음, 1-12). 몸통 지름 58cm·깊이 44cm(200L 드럼 높이 약 88cm의 반), 각목 목 5×5cm 굵기·몸통 위로 82cm",
  colors=["#4A6A86", "#8B4A2B", "#B98A5A", "#9DA3A6"],
  condition="빛바랜 남청색 칠, 잘린 테두리는 밝은 쇠 단면에 줄질 자국, 몸통 곳곳 녹 반점과 찌그러짐 2~3곳. 3화부터 국자로 친 테두리 한 곳이 반들반들",
  shape="반으로 자른 드럼통 아랫동을 세워, 막힌 바닥 원판을 앞(울림판)으로 향하게 둔다. 열린 쪽은 연주자 몸 쪽. 각목 하나가 원판 앞면 세로 중심선을 따라 아래에서 위로 지나 몸통 위로 솟아 목이 되고, 아래 끝은 바닥에 닿아 받침(엔드핀)이 된다. "
        "몸통 가운데 둘레에 드럼통 굴림 테(볼록한 띠) 한 줄. 원판 앞면 가운데쯤 나무토막 줄받침, 굵은 줄 4개가 각목 꼭대기 나무못 4개에서 원판 아래쪽 철사 고리까지. 테두리(잘린 둘레)가 둥글게 드러나 국자로 칠 수 있다",
  role="덕수의 목소리. 최 계장의 걸음을 멈춘 소리(2-6) → 보고서(3-12) → 본선 '새벽'의 트럭 엔진(3-20). 줄이 자주 끊겨 덕수가 벌렁 넘어지는 개그(2-1)",
  ref="https://en.wikipedia.org/wiki/Recycled_Orchestra_of_Cateura (카테우라 첼로=오일 드럼), https://www.pachmas.com/info/products/metal_drums/01thcyl/216.htm (드럼 치수, 검색 요약). 가로로 잘라 원판을 앞판으로 쓰는 구조는 디자인 판단(미확인)",
  en=dict(name="'Ttungbo', a homemade cello made from half of a steel oil drum",
          shape="the bottom half of a steel oil drum cut crosswise and stood upright with its closed round base facing forward as the soundboard, "
                "a long square pine beam running vertically down the front of the round base as the neck and fingerboard, its lower end touching the floor as an end pin, "
                "a small wooden block bridge on the round base, four thick strings from four wooden pegs at the top of the beam down to an iron wire loop near the bottom of the base, "
                "one raised rolling hoop ring around the middle of the drum body, the cut rim of the drum exposed all around, an old worn cello bow shown beside it",
          material="steel oil drum, pine beam, piano wire strings, wooden pegs",
          size="140cm tall overall, drum body 58cm diameter and 44cm deep, beam 5cm square",
          condition="faded blue-gray paint, the cut rim bright raw steel with file marks, rust spots and two or three dents"),
  notes="대본: 기름통을 반으로 가름, 각목을 박음, 은주 키만 함, 굵은 줄. 2-1 피아노를 갈라 '이거 한 대면 일 년은 간다' → 끊어진 줄을 피아노 쇠줄로 바꾼다고 해석(추측). 활은 대본에 형태 없음(낡은 첼로 활로 둠, 추측)",
  states=[
    S("ttungbo__s1_making", "제작 중(1-12)", ["1-12"],
      "곽 영감이 기름통을 쇠톱으로 반으로 가르는 중. 잘린 단면이 날카롭게 번쩍, 각목은 아직 박히지 않음",
      name="a steel oil drum being cut in half crosswise with a hacksaw", shape="the drum lying on a workbench, a hacksaw cut halfway around its middle, a square pine beam waiting beside it",
      material="steel oil drum, pine beam", size="drum 57cm diameter, 88cm tall before cutting", condition="faded blue-gray paint, bright fresh saw cut, rust spots"),
    S("ttungbo__s2_complete", "완성(굵은 줄)", R("1-12", "1-14", "2-1..2-4", "2-6", "2-10", "2-14", "2-18"),
      "각목 목을 박고 굵은 줄을 건 완성 모습. 2-1 몽타주 4·6에서 줄이 '팅!' 끊어져 덕수 반대쪽으로 튐 — 그 컷만 줄 하나가 허공에 휨"),
    S("ttungbo__s3_piano_wire", "피아노 쇠줄로 갈아 낀 뒤 + 국자 친 테두리", R("3-5", "3-6", "3-9", "3-10", "3-18..3-21", "3-23", "3-25", "3-27"),
      "줄 4개가 피아노 쇠줄(밝은 은색 강선, 저음 2줄은 구리색 감은 줄)로 바뀜(추측). 3-6부터 덕수가 순례 할머니 국자로 테두리를 침 — 오른쪽 위 테두리 한 곳이 반들반들",
      condition="faded blue-gray paint, rust spots, the strings now bright piano wire with the two lowest copper-wound, one spot on the upper right rim polished shiny from being struck with a ladle",
      colors=["#4A6A86", "#8B4A2B", "#B98A5A", "#C7844A"]),
  ]),

P("kkwaekkwaegi", "꽥꽥이(배수관 트럼펫)", "A",
  R("1-12", "1-14", "2-1..2-4", "2-10", "2-14", "2-18", "3-5", "3-6", "3-9", "3-10", "3-18..3-21", "3-23", "3-25", "3-27"),
  aliases=["꽥꽥이", "배수관 트럼펫", "배수관"],
  material="아연도금 쇠 배수관(구부러진 것), 양철 깔때기 나팔, 쇠철사 감기, 고무 조각, 검은 절연 테이프(입 대는 끝)",
  size="관 지름 3cm, 펼치면 약 110cm, 구부린 상태 전체 길이 55cm·폭 18cm. 깔때기 입구 지름 16cm",
  colors=["#A9ADA8", "#D8DCDD", "#2B2B2B", "#7A3E2A"],
  condition="회색 아연 도금이 군데군데 벗겨져 갈색 녹 반점. 깔때기는 밝은 양철에 찌그러진 자국 하나. 이음매에 쇠철사 감기와 검은 고무 조각",
  shape="쇠 배수관이 납작한 S자(두 번 꺾임)로 구부러져 있고, 한쪽 끝(입 대는 쪽)은 검은 절연 테이프를 세 바퀴 감아 무디게, 다른 끝에 양철 깔때기를 끼워 나팔로 삼았다. "
        "관과 깔때기 이음매를 쇠철사로 감아 묶었다. 1-12 수리 뒤: 이음매 왼쪽(연주자가 들었을 때 왼쪽)에 철사 한 바퀴 더, 그 위 검은 고무 조각 덧댐",
  role="미자의 악기, 미자의 '큰 소리'. 처음엔 바람이 새서 '피시식' → 은주의 귀로 이음매를 찾아 '꽤애액'. 3화 '한낮'의 바람, 줄 끊김 때 시간을 버는 바람(3-21)",
  ref="형태 참고만: https://en.wikipedia.org/wiki/Recycled_Orchestra_of_Cateura (배수관 금관), https://www.thomannmusic.com/blog/inspire/landfill-melodies. 한국 배수관 재질·S자 형태·테이프는 디자인 판단(미확인)",
  en=dict(name="'Kkwaekkwaegi', a homemade trumpet made from a bent drainpipe",
          shape="a 3cm-wide galvanized iron drainpipe bent into a flattened S with two bends, the mouth end wrapped three times with black electrical tape, "
                "a tin funnel jammed onto the other end as the bell, the joint between pipe and funnel bound with iron wire, "
                "an extra turn of wire and a small black rubber patch on the left side of the joint",
          material="galvanized iron pipe, tinplate funnel, iron wire, black rubber, black tape",
          size="about 55cm long and 18cm wide as bent, funnel bell 16cm across",
          condition="gray zinc coating flaking off in places with brown rust spots, one dent in the funnel"),
  notes="'이음매 왼쪽'은 미자가 들고 불 때 연주자 기준 왼쪽으로 고정",
  states=[
    S("kkwaekkwaegi__s1_leaking", "처음(바람 샘, 1-12 수리 전)", ["1-12"],
      "곽 영감이 구석에서 집어 든 그대로. 이음매에 철사 한 바퀴만, 왼쪽에 틈 — 바람이 새는 자리(고무 조각 없음)",
      shape="a 3cm-wide galvanized iron drainpipe bent into a flattened S with two bends, the mouth end wrapped with black electrical tape, a tin funnel jammed onto the other end as the bell, only one loose turn of iron wire at the joint with a small gap on its left side",
      colors=["#A9ADA8", "#D8DCDD", "#2B2B2B", "#7A3E2A"]),
    S("kkwaekkwaegi__s2_fixed", "수리 뒤(철사 한 바퀴 더 + 고무 조각)", R("1-12", "1-14", "2-1..2-4", "2-10", "2-14", "2-18", "3-5", "3-6", "3-9", "3-10", "3-18..3-21", "3-23", "3-25", "3-27"),
      "이음매 왼쪽에 철사를 한 번 더 감고 검은 고무 조각 덧댐. 이후 고정 모습"),
  ]),

P("bone_drum", "뼈다귀 북(X선 필름 북)", "A",
  R("1-12", "1-14", "2-1..2-4", "2-10", "2-14", "2-18", "3-5", "3-6", "3-9", "3-10", "3-18..3-21", "3-25"),
  aliases=["뼈다귀 북", "X선 필름 북", "페인트 통 북", "페인트 통"],
  material="원형 철제 페인트 통(18L 짜리), 씻어 말린 X선 필름(가죽 대신), 고무줄·쇠철사, 갈색 포장 테이프",
  size="통 위 지름 30cm·아래 지름 28cm·높이 34cm, 철사 손잡이. 필름 한 장 35×43cm를 덮어 옆으로 5cm 내려옴",
  colors=["#C9C3B4", "#3E4A55", "#E8EEF2", "#8A6A3E"],
  condition="통 겉은 흘러내린 페인트 자국(흰·회색)과 녹 반점. 필름 가장자리를 둘레에서 쇠철사로 조이고, 그 위를 갈색 포장 테이프로 겹겹이 감음. 필름 표면에 북채 자국 잔흠",
  shape="원통형 페인트 통 위를 반투명 회청색 X선 필름 한 장이 북 가죽처럼 팽팽하게 덮는다. 빛에 비추면 필름 속에 하얀 손뼈(손가락뼈 다섯 개가 활짝 편 손)가 흐릿하게 비친다. "
        "필름 가장자리는 통 둘레로 접혀 내려와 쇠철사로 한 바퀴 조이고 갈색 포장 테이프를 겹겹이 감았다. 통 양옆에 철사 손잡이. 글자·이름표·의료 표시는 없다",
  role="동민의 북, '쿠웅-따악', 심장 소리. 3-19 본선에서 동민이 손가락으로 두 번 '톡톡' — 엄마의 '괜찮아' 복선 회수",
  ref="https://en.wikipedia.org/wiki/Recycled_Orchestra_of_Cateura (X선 필름+포장 테이프), https://mms.mckesson.com/product/381330 (필름 35×43cm, 검색 요약). 한국 18L 페인트 통 치수는 미확인(해외 5갤런 통 기준)",
  en=dict(name="'the bone drum', a homemade drum made from a paint can and an X-ray film",
          shape="a round steel paint pail slightly tapered toward the bottom with a wire bail handle, its open top covered tight like a drumhead with one sheet of translucent blue-gray X-ray film "
                "in which a faint white hand skeleton with five spread finger bones shows through, the film edge folded down the sides, bound with iron wire and wrapped many times with brown packing tape, "
                "no letters, no names, no medical markings on the film",
          material="steel paint can, translucent X-ray film, iron wire, brown packing tape",
          size="30cm across the top tapering to 28cm at the bottom, 34cm tall, film sheet 35 by 43cm",
          condition="old white and gray paint drips down the outside, rust spots, tiny stick marks on the film"),
  notes="X선 필름은 '뼈가 비치는 흐릿한 회청색 필름', 의료 정보·이름 글자 없음(지시). 북채는 drumstick_spoons",
  states=[
    S("bone_drum__s1_film_drying", "제작 — 씻어 말리는 X선 필름(1-12)", ["1-12"],
      "작업대 한쪽 비눗물 대야, 빨랫줄에 깨끗이 씻어 말린 X선 필름 몇 장(병원 고물). 아직 통에 씌우기 전",
      name="several washed X-ray film sheets drying on a clothesline above a basin of soapy water",
      shape="four rectangular translucent blue-gray X-ray film sheets hung with wooden clothespins on a thin line, faint white bones showing in them (a hand, ribs), a dented metal basin of soapy water below",
      material="X-ray film, wooden clothespins, cotton line, metal basin", size="each sheet 35 by 43cm, basin 45cm across",
      condition="films washed clean and still dripping, no letters or markings", colors=["#3E4A55", "#E8EEF2", "#A7ACB0", "#C9A06A"]),
    S("bone_drum__s2_complete", "완성", R("1-12", "1-14", "2-1..2-4", "2-10", "2-14", "2-18", "3-5", "3-6", "3-9", "3-10", "3-18..3-21", "3-25"),
      "페인트 통 위에 필름을 씌운 완성 모습. 해를 향해 들면 손뼈가 비침(1-12), 3-19 동민 손가락 극접사에서 뼈 그림자"),
  ]),

P("can_violin_2", "깡통 바이올린 2호(봉구)", "A",
  R("3-9", "3-10", "3-18..3-20", "3-25", "3-27"),
  aliases=["깡통 바이올린 2호", "2호"],
  material="양철 분유 깡통(동그리보다 작은 것, 상표 종이 벗김), 나무 숟가락 목, 구부린 포크 줄받침, 피아노 쇠줄(가는 것) 4, 나무못 4",
  size="전체 약 48cm. 깡통 지름 13cm·길이 15cm, 숟가락 40cm",
  colors=["#C4C8CA", "#A0522D", "#D4AE78", "#A7ACB0"],
  condition="녹은 거의 없고 테두리에 점 녹 몇 개, 몸통 한쪽에 오목한 찌그러짐 1곳(동그리와 구분점), 새 숟가락이라 밝은 나무색",
  shape="동그리와 같은 구조(깡통을 눕혀 몸통, 앞 원판 위쪽에 숟가락 자루 목, 숟가락 머리에 나무못 4, 포크 날 4개 줄받침, 뒤 테두리 철사 고리). 차이: 더 작은 깡통, 옆구리에 찌그러짐 하나, 녹 띠 대신 점 녹, 줄은 반짝이는 가는 피아노 쇠줄",
  role="3화 새 단원 봉구의 악기. 곽 영감이 공방에서 은주가 고른 깡통으로 만듦(3-9). '아침'의 동, 동, 챙과 비닐 소리",
  ref="미확인(디자인은 동그리 구조를 따름). 피아노 쇠줄은 decisions.md G4",
  en=dict(name="can violin No. 2, a smaller homemade violin made from a milk-powder tin can",
          shape="same construction as Donggeuri: a smaller milk-powder tin can laid on its side as the body, a wooden cooking spoon neck entering under the top edge of the front end, "
                "four wooden pegs through the spoon bowl, a bent stainless fork standing as the bridge with four tines up, four thin bright piano-wire strings to an iron wire loop on the rear rim, "
                "one shallow dent on the side of the can",
          material="tinplate can, pale wooden spoon, stainless fork, piano wire",
          size="about 48cm long, can 13cm diameter by 15cm", condition="almost no rust, only a few rust dots on the rims, one dent on the side, fresh pale spoon wood"),
  notes="3-19 '분유 깡통 세 대' — 2·3호도 분유 깡통. 동그리와는 크기·찌그러짐·녹 모양으로만 구분. 3-9 효과음 '끼릭(줄감개)'은 decisions.md G4 '줄감개→나무못' 교정에 따라 나무못으로 그림",
  states=[S("can_violin_2__s1", "완성(3-9 이후)", R("3-9", "3-10", "3-18..3-20", "3-25", "3-27"), "변화 없음")]),

P("can_violin_3", "깡통 바이올린 3호(영란)", "A",
  R("3-9", "3-10", "3-18..3-20", "3-25", "3-27"),
  aliases=["깡통 바이올린 3호", "3호"],
  material="양철 분유 깡통(키가 큰 것, 상표 종이 벗김), 나무 숟가락 목, 구부린 포크 줄받침, 피아노 쇠줄(가는 것) 4, 나무못 4",
  size="전체 약 55cm. 깡통 지름 12cm·길이 20cm, 숟가락 40cm",
  colors=["#B0B5B8", "#7E4426", "#B8875A", "#A7ACB0"],
  condition="몸통 중간에 둘레 한 줄로 갈색 녹 띠(가운데 띠, 동그리는 테두리 녹), 어두운 나무색 숟가락, 깡통 바닥 원판이 살짝 불룩",
  shape="동그리와 같은 구조. 차이: 가늘고 긴 깡통, 몸통 가운데 둘레 녹 띠, 짙은 숟가락, 반짝이는 가는 피아노 쇠줄",
  role="3화 새 단원 영란의 악기(3-9). '아침'과 '한낮' 합주",
  ref="미확인(디자인은 동그리 구조를 따름). 피아노 쇠줄은 decisions.md G4",
  en=dict(name="can violin No. 3, a slender homemade violin made from a tall milk-powder tin can",
          shape="same construction as Donggeuri: a tall narrow milk-powder tin can laid on its side as the body, a darker wooden cooking spoon neck entering under the top edge of the front end, "
                "four wooden pegs through the spoon bowl, a bent stainless fork standing as the bridge with four tines up, four thin bright piano-wire strings to an iron wire loop on the rear rim",
          material="tinplate can, dark wooden spoon, stainless fork, piano wire",
          size="about 55cm long, can 12cm diameter by 20cm", condition="a band of brown rust around the middle of the can, the can's end slightly bulging"),
  notes="2호와 같음",
  states=[S("can_violin_3__s1", "완성(3-9 이후)", R("3-9", "3-10", "3-18..3-20", "3-25", "3-27"), "변화 없음")]),

P("pot_lid_cymbals", "냄비 뚜껑 심벌(경호·경민)", "A",
  R("3-9", "3-10", "3-18..3-20", "3-25", "3-27"),
  aliases=["냄비 뚜껑 심벌", "냄비 뚜껑", "냄비 뚜껑 두 개"],
  material="양은(노란 아노다이징 알루미늄) 냄비 뚜껑 2개, 꼭지는 검은 수지 손잡이(꼭지 재질은 미확인)",
  size="각 지름 22cm·둥근 볼록 높이 3cm, 꼭지 지름 3cm",
  colors=["#D9C9A0", "#C7CBC9", "#2B2B2B", "#9C8B60"],
  condition="노르스름한 양은 빛, 그을음·찌그러짐 자국, 두 뚜껑의 찌그러진 자리가 서로 다름(하나는 테두리, 하나는 가운데)",
  shape="볼록한 원형 냄비 뚜껑 두 장, 가운데 꼭지를 손잡이로 쥐고 맞부딪친다. 테두리는 냄비에 얹히게 살짝 꺾여 있다",
  role="쌍둥이의 '촤앙!' — '아침'의 쇳소리, 대상 발표 뒤 촤앙(3-27)",
  ref="https://sayhikorean.com/?p=12522 (양은=노란 알루미늄, 검색 요약). 뚜껑 지름은 미확인",
  en=dict(name="a pair of pot-lid cymbals", shape="two domed round aluminum saucepan lids held by their center knobs, the rims slightly flared",
          material="yellowish aluminum, black bakelite knobs", size="each 22cm across, domed 3cm", condition="soot marks and small dents, each lid dented in a different spot"),
  states=[S("pot_lid_cymbals__s1", "쌍둥이가 받은 그대로", R("3-9", "3-10", "3-18..3-20", "3-25", "3-27"), "변화 없음")]),

P("bottle_xylophone", "병 실로폰(순이·석이)", "A",
  R("3-9", "3-10", "3-18..3-20", "3-25"),
  aliases=["병 실로폰", "빈 병 여섯 개", "빈 병"],
  material="빈 유리병 6개(투명·연하늘색·갈색 섞임, 초록 병 없음 — 초록 소주병은 1994년부터, 상표 라벨 없음), 물, 두드리는 쇠 숟가락 2",
  size="병 높이 20~25cm, 지름 6~7cm. 병마다 물 높이가 다름(가장 많이 3/4 ~ 가장 적게 1/5)",
  colors=["#E3EEF0", "#BFD8E0", "#7A4E2A", "#8FB8D8"],
  condition="라벨을 떼어 낸 자국이 뿌옇게, 병목에 작은 이 빠짐 하나, 깨끗이 씻음",
  shape="크기와 색이 조금씩 다른 빈 병 여섯 개를 한 줄로 세우고 물 높이를 계단처럼 다르게 채움. 숟가락으로 두드림. 상표·글자 없음",
  role="순이·석이의 '똥, 딩, 당' — '한낮'의 웃음소리. 동민 '근데 누나, 병도 노래해!'",
  ref="https://www.insight.co.kr/news/473379 (초록 소주병 1994년부터, 검색 요약). 병 크기는 미확인",
  en=dict(name="a bottle xylophone", shape="six empty glass bottles of slightly different shapes standing in a row, each filled with water to a different height like steps, two metal spoons as beaters, no labels",
          material="clear, pale blue and brown glass, no green bottles, water", size="bottles 20 to 25cm tall", condition="cloudy marks where labels were peeled off, one tiny chip on a bottle neck, washed clean"),
  notes="12세 기준: 깨진 병 없음",
  states=[S("bottle_xylophone__s1", "물 높이를 맞춘 완성", R("3-9", "3-10", "3-18..3-20", "3-25"), "3-9 은주가 두드려 듣고 물을 한 모금 더·덜")]),

P("baton", "지휘봉(숟가락 자루 막대)", "A",
  R("1-14", "2-1", "2-2", "2-4", "2-10", "2-14", "2-18", "3-10", "3-18..3-21", "3-25"),
  aliases=["지휘봉", "숟가락 자루 지휘봉", "나무 숟가락 손잡이"],
  material="나무 숟가락 자루를 매끈하게 깎은 막대(밝은 나무)",
  size="길이 32cm, 굵기 손잡이 쪽 1.4cm → 끝 0.5cm",
  colors=["#D6B07A", "#B48A55", "#8A6A45"],
  condition="곽 영감이 칼로 깎아 사포로 매끈하게, 손잡이 쪽에 숟가락 머리를 잘라 낸 납작한 단면이 남음",
  shape="한쪽은 납작하고 넓은 손잡이(숟가락 머리를 잘라 낸 자리), 끝으로 갈수록 가늘어지는 곧은 막대",
  role="곽 영감이 선영에게 준 지휘봉. 국솥에 퐁당(2-1), 본선에서 떨리다 멎음(3-19), 줄 끊김에도 내려가지 않음(3-21)",
  ref="https://en.wikipedia.org/wiki/Baton_(conducting) (지휘봉 30~41cm, 검색 요약)",
  en=dict(name="a conductor's baton carved from a wooden spoon handle",
          shape="a straight stick tapering to a fine tip, the grip end flat and wider where the spoon bowl was cut off",
          material="pale wood, hand-carved and sanded smooth", size="32cm long", condition="smooth with faint knife facets near the grip"),
  states=[
    S("baton__s1", "처음(1-14 받음)", R("1-14", "2-2", "2-4", "2-10", "2-14", "2-18", "3-10", "3-18..3-21", "3-25"), "변화 거의 없음, 손때만 늘어남"),
    S("baton__s2_soup", "국솥에 빠졌다 건짐(2-1)", ["2-1"],
      "순례 할머니가 국자로 건져 행주에 탁탁 턴 직후 — 젖어 번들, 국물 방울", condition="wet and glistening with broth drops after being fished out of a soup pot"),
  ]),

P("kwak_violin", "곽 영감의 진짜 바이올린", "A",
  R("3-15"),
  aliases=["진짜 바이올린", "곽 영감 바이올린", "다락의 바이올린"],
  material="가문비나무 앞판·단풍나무 뒤판(꿀 빛깔 니스), 흑단 지판·줄감개, 낡은 천 싸개",
  size="표준 4/4 바이올린: 전체 59cm, 몸통 35.5cm, 폭 20cm",
  colors=["#C98B3C", "#E3B26A", "#2A2422", "#B8A68A"],
  condition="오래 보관해 니스가 깊은 꿀 빛, 흠집 거의 없음. 싸 둔 천은 누렇게 바래고 먼지",
  shape="정통 바이올린. 머리 소용돌이, 줄 4개, f자 울림구멍 2개, 받침·턱받침. 낡은 천으로 한 겹씩 쌌다가 푼다",
  role="곽 영감이 평생 처음부터 끝까지 혼자 깎아 아무에게도 팔지 않은 한 대. 은주가 '제 소리는 이거예요'라며 돌려줌 → 곽 영감의 큰 웃음. 1-9 영감의 시선이 다락으로",
  ref="https://fiddlerman.com/what-size-violin-should-i-get/ (4/4 치수, 검색 요약)",
  en=dict(name="a handmade full-size violin with honey-colored varnish",
          shape="a classic violin with scroll, four strings, two f-holes, bridge and chinrest, shown beside the old cloth it was wrapped in",
          material="spruce top, flamed maple back, ebony fittings, a faded cloth wrap", size="59cm long, body 35.5cm",
          condition="deep warm honey varnish glowing, almost no scratches, the wrapping cloth yellowed and dusty"),
  offscreen="1-9(다락으로 가는 시선만, 바이올린은 안 보임)",
  states=[
    S("kwak_violin__s1_wrapped", "다락의 천 꾸러미", ["3-15"], "낡은 천에 싸인 길쭉한 꾸러미. 사다리로 내려옴",
      shape="a long bundle wrapped in several layers of old faded cloth tied with string, the violin shape only hinted", condition="the cloth yellowed and dusty"),
    S("kwak_violin__s2_unwrapped", "천을 푼 바이올린", ["3-15"], "백열등 아래 꿀 빛깔. 끝에 작업대 위 동그리 옆에 나란히 눕힘"),
  ]),

P("broken_violin_body", "목 부러진 바이올린 몸통", "A",
  ["1-3"],
  aliases=["목 부러진 바이올린", "나무 몸통"],
  material="바이올린 몸통(가문비 앞판·단풍 옆판), 니스가 거의 벗겨짐",
  size="몸통 길이 35.5cm, 폭 20cm, 두께 4cm(목 없음)",
  colors=["#9A6A3A", "#6E4A2A", "#D0B48C", "#3A2A1E"],
  condition="목이 부러져 없고 그 자리에 쪼개진 나무 끝. 앞판에 세로 금 한 줄(약 12cm). 줄·줄받침 없음. 둘레 고물은 먼지투성이인데 이것만 먼지 하나 없이 닦여 있음",
  shape="허리가 잘록한 바이올린 몸통만. f자 울림구멍 2개, 목 이음 자리가 부러져 거칠다",
  role="'사람이 버렸지. 소리가 버린 게 아니다.' / '이건 아직 소리가 남았다' 첫 등장. 은주가 '안에서 한 번 더 울려요'. 동그리가 아님(동그리를 만들 생각의 씨앗)",
  ref="미확인",
  en=dict(name="the body of a broken violin with its neck snapped off",
          shape="only the narrow-waisted violin body with two f-holes, splintered wood where the neck used to be, no strings, no bridge, a single crack running along the top",
          material="spruce and maple, most varnish worn off", size="35.5cm long, 20cm wide",
          condition="neck missing, one 12cm crack in the top, but wiped completely free of dust"),
  states=[S("broken_violin_body__s1", "선반 위", ["1-3"], "변화 없음")]),

P("tuning_fork_necklace", "은색 소리굽쇠 목걸이", "A",
  R("1-5", "1-11", "2-4", "2-18", "2-19", "2-25", "3-3..3-10", "3-15", "3-17..3-22", "3-24..3-30", "3-34"),
  aliases=["소리굽쇠", "소리굽쇠 목걸이", "은색 소리굽쇠"],
  era="1987~88 서울(회상 1970년대, 에필로그 2003)",
  material="니켈 도금 강철 소형 소리굽쇠(라 A 음), 가는 은색 줄 사슬",
  size="소리굽쇠 길이 10cm(손잡이 3.5cm, 가지 2개 각 6.5cm, 둥근 막대 굵기 0.36cm), 사슬 길이 60cm·굵기 0.1cm",
  colors=["#D5D9DE", "#F2F4F7", "#9AA0A6", "#B8BEC6"],
  condition="잘 닦인 은빛, 손잡이 쥐는 자리만 도금이 살짝 닳아 짙은 회색, 사슬 고리 하나가 조금 벌어짐",
  shape="U자 바닥에서 갈라진 곧은 가지 두 개, 아래 손잡이 끝에 작은 둥근 꼭지와 고리, 고리에 가는 사슬. 각인·글자 없음",
  role="엄마(외할아버지 라디오 수리점)의 유품. '세상에서 제일 똑바른 소리'. 조율의 기준(1-11·2-4). 2-25 빼서 라디오 상자에 → 3-3 만석이 다시 걸어 줌 → 3-22 줄 교체 때 '음 줘'",
  ref="https://www.stretta-music.dk/tuning-fork-km-168-nr-457627.html (A440 소리굽쇠 약 10.5cm, 검색 요약). 목걸이 고리·사슬은 디자인 판단",
  en=dict(name="a small silver tuning-fork pendant on a thin chain",
          shape="a U-shaped tuning fork of round steel rod with two straight tines and a short stem ending in a small round knob with a tiny ring, threaded on a fine silver chain, no engraving",
          material="nickel-plated steel, fine steel chain", size="fork 10cm long with 0.36cm round tines, chain 60cm", condition="well polished, plating slightly worn on the stem where it is held"),
  notes="옷 속 착용(보이지 않음) 씬은 scenes에서 뺐다 — scene_presets characters.note 기준(1-1~2-24 대부분 '착용, 옷 속')",
  states=[
    S("tuning_fork_necklace__s1_worn", "착용 — 꺼내 쓸 때(옷 속에서 꺼냄)", R("1-5", "1-11", "2-4"),
      "평소엔 점퍼 속. 꺼내 무릎에 톡 치고 귀나 깡통에 댐"),
    S("tuning_fork_necklace__s2_under_blouse", "블라우스 안 — 사슬만 보임", R("2-18", "2-19"),
      "흰 블라우스 깃 위로 가는 사슬만, 소리굽쇠는 블라우스 안",
      name="a fine silver chain around a girl's neck disappearing under a white blouse collar", shape="only the thin chain visible at the collar, the pendant hidden inside the blouse"),
    S("tuning_fork_necklace__s3_in_box", "라디오 상자 속 — 엉킨 사슬", R("2-25", "3-3"),
      "은주 손바닥에서 상자 안 라디오 옆으로 떨어짐, 가는 사슬이 사르르 엉키며 쌓임. 3-3 만석이 긴 손가락으로 엉킨 데를 하나하나 품",
      shape="the tuning fork lying in a wooden box beside an old transistor radio, its fine chain tangled in a small heap", condition="polished silver, chain knotted"),
    S("tuning_fork_necklace__s4_rehung", "만석이 다시 걸어 줌 — 쇄골 위", R("3-3..3-10", "3-15", "3-17..3-22", "3-24..3-30"),
      "3-3 사슬을 은주 목에 걸어 줌, 차가운 쇠가 쇄골에 닿음. 이후 옷 위로 보이게 착용, 본선 흰 원피스 위"),
    S("tuning_fork_necklace__s0_mother", "회상 — 라디오 수리점에서 젊은 엄마의 손가락이 튕김", ["3-21"],
      "겹침 장면(세피아, 흐릿하게). 같은 소리굽쇠, 더 새것", condition="brand new and bright", era="1970s Seoul"),
    S("tuning_fork_necklace__s5_epilogue", "15년 뒤(2003)", ["3-34"], "어른 은주 목에. 손잡이 도금이 더 닳음",
      condition="plating worn further on the stem, still polished", era="2003 Seoul"),
  ]),

P("mother_radio", "엄마의 고장 난 트랜지스터라디오", "A",
  R("1-5", "1-10", "2-11", "2-25", "3-3", "3-7", "3-34"),
  aliases=["엄마의 라디오", "트랜지스터라디오", "라디오", "엄마의 고장 난 라디오"],
  era="1970년대 제품, 1987~88 서울(에필로그 2003)",
  material="빨간 칠 케이스(칠 아래 회색 바탕), 앞면 스피커 자리의 은색 타공 금속판, 갈색 가죽 손잡이 끈, 옆면 다이얼 2(주파수·볼륨), 뒤판 일자 나사 4",
  size="손바닥만 함: 가로 15cm·세로 9.5cm·두께 4.5cm, 손잡이 끈 길이 12cm",
  colors=["#A8322E", "#C9CCCE", "#5A3A24", "#8C8C88"],
  condition="빨간 칠 모서리가 벗겨져 회색 바탕이 드러남(대본 1-5), 가죽 손잡이 끈이 갈라짐, 눈금 창 플라스틱이 누렇게 바램",
  shape="가로로 긴 직사각 상자, 모서리 둥글림. 빨간 칠 몸체, 앞면 왼쪽 2/3는 은색 타공 금속판(스피커). 오른쪽 옆면에 둥근 다이얼 2개(주파수·볼륨), 앞면 오른쪽 위에 작은 눈금 창(눈금선만, 숫자·글자 없음). 윗면에 가죽 손잡이 끈과 접힌 은색 안테나(안테나는 미확인). 뒤판은 일자 나사 4개(동전으로 푼다)",
  role="엄마의 부재. 은주가 밤마다 고쳐 보려 함, 가끔 지직거리며 허밍 네 음(1-5, 3-7). 「섬의 하루」 '저녁' 독주. 에필로그 연주 뒤 다시 허밍이 새어 나옴(3-34)",
  ref="https://webzine.nfm.go.kr/2017/03/28/%EB%9D%BC%EB%94%94%EC%98%A4-%EC%A0%84%EC%84%B1%EC%8B%9C%EB%8C%80/ (국립민속박물관 웹진: 빨간 본체·옆면 다이얼·은색 금속판 반영. 같은 글의 '검은 가죽 커버'는 대본 1-5 '모서리 칠이 벗겨지고 손잡이 가죽이 갈라져'와 맞지 않아 넣지 않음). 안테나·뒤판 나사는 미확인",
  en=dict(name="an old pocket transistor radio",
          shape="a rounded rectangular box with a red painted body, a perforated silver metal speaker plate on the left two thirds of the front, two round dials (tuning and volume) on the right side edge, a small dial window with tick marks only, "
                "a leather carrying strap on top, a folded silver telescopic antenna, four slotted screws on the back panel",
          material="red painted case, silver metal speaker plate, brown leather strap", size="15 by 9.5 by 4.5cm",
          condition="red paint chipped off at the corners showing gray underneath, the leather strap cracked, the dial window yellowed"),
  states=[
    S("mother_radio__s1_broken", "고장 — 은주가 고쳐 보는 라디오", R("1-5", "1-10", "2-11", "2-25", "3-3", "3-7"),
      "1-5 동전으로 뒤판 나사를 풀고 엉킨 선을 손끝으로 밂(뒤판 열린 컷: 안에 초록 기판·작은 부품·색 전선). 3-7 켜짐(딸깍, 지직)"),
    S("mother_radio__s1b_open_back", "뒤판을 연 모습(1-5)", ["1-5"],
      "뒤판을 떼어 낸 내부: 초록 기판, 작은 원통 부품, 빨강·노랑 전선 몇 가닥이 엉킴, 건전지 칸",
      shape="the back panel removed showing the inside: a green circuit board, small cylindrical parts, a few tangled red and yellow wires, a battery compartment, the four slotted screws and a coin lying beside it"),
    S("mother_radio__s2_epilogue", "15년 뒤 — 의자 위, 허밍이 새어 나옴(2003)", ["3-34"],
      "작은 무대 한쪽 접이식 의자 위. 여전히 고장 난 채, 잘 닦여 있음. 칠은 더 바램",
      condition="still broken but carefully wiped clean, red paint more faded, chipped corners showing gray, cracked leather strap", era="2003 Seoul"),
  ]),

P("radio_box", "라디오 상자(나무 상자)", "A",
  R("2-11", "2-25", "3-3"),
  aliases=["라디오 상자", "나무 상자"],
  material="얇은 소나무 판자 상자, 경첩 뚜껑, 작은 놋쇠 걸쇠",
  size="가로 26cm·세로 18cm·높이 12cm, 판자 두께 1cm",
  colors=["#A88458", "#6E5236", "#C8A55A"],
  condition="손때로 모서리가 거뭇, 뚜껑 가장자리에 긁힘, 걸쇠는 '딸깍' 소리가 나게 살짝 헐거움",
  shape="뚜껑이 경첩으로 열리는 단순한 직사각 나무 상자. 앞쪽에 작은 놋쇠 고리 걸쇠. 안은 칸막이 없음, 라디오와 소리굽쇠가 함께 들어감",
  role="엄마의 물건을 두는 자리. 은주가 소리굽쇠를 넣으며 포기(2-25) → 만석이 꺼내 다시 걸어 줌(3-3)",
  ref="미확인",
  en=dict(name="a small plain wooden keepsake box", shape="a simple rectangular box with a hinged lid and a tiny brass hook latch on the front, no dividers inside, shown closed and open",
          material="thin pine boards, brass hinges and latch", size="26 by 18 by 12cm", condition="corners darkened by handling, scratches on the lid edge"),
  states=[
    S("radio_box__s1_closed", "선반 위 닫힌 상자", R("2-11", "2-25", "3-3"), "쪽방 머리맡 선반"),
    S("radio_box__s2_open", "열린 상자 — 라디오와 엉킨 사슬", R("2-25", "3-3"), "위에서 내려다본 상자 안: 라디오 옆에 소리굽쇠, 가는 사슬이 엉켜 쌓임",
      shape="the box open seen from above, an old pocket transistor radio inside and beside it a small silver tuning fork with its fine chain tangled in a heap"),
  ]),

P("empty_violin_case", "선영의 빈 바이올린 케이스", "A",
  R("1-6", "1-7", "1-8", "2-1", "2-8", "2-9", "3-10"),
  aliases=["빈 바이올린 케이스", "검은 바이올린 케이스", "선영의 케이스"],
  material="나무 틀에 검은 인조가죽(레자) 씌움, 안감 붉은 벨벳, 금속 잠금쇠 2, 가죽 손잡이",
  size="길이 78cm, 폭 넓은 쪽 25cm·좁은 쪽 13cm, 두께 11cm",
  colors=["#1E1E22", "#9E1F2E", "#C9C2B0", "#B0A890"],
  condition="모서리 인조가죽이 닳아 회갈색 속살, 잠금쇠 하나가 헐거워 잘 풀림(1-6 철컥). 안쪽 벨벳은 바이올린 모양으로 움푹 꺼진 자리가 반질, 희미한 송진 가루(흰 가루)",
  shape="한쪽이 넓고 한쪽이 좁은 바이올린 모양(물방울형) 케이스. 열면 붉은 벨벳 안에 바이올린 모양 자국, 활 걸이 홈, 작은 덮개 칸. 바이올린은 없고 악보 몇 장과 알록달록 사탕(2-8 사탕 봉지)",
  role="선영의 바이올린이 전당포에 있다는 것('쉬고 있어요'). 뚜껑을 닫으면 '텅' — 속이 빈 소리. 2-8 만석과 부딪혀 '텅', 만석의 눈이 머묾. 3-10 만석의 '만복전당포'",
  ref="미확인",
  en=dict(name="an empty black violin case", shape="a shaped violin case wide at one end and narrow at the other, two metal latches and a leather handle, shown open: red velvet lining pressed into the hollow shape of a violin, a bow holder groove, a small lidded pocket, no violin inside, a few sheets of music and colorful wrapped candies lying in the hollow",
          material="black leatherette over wood, red velvet lining, metal latches", size="78cm long, 25cm wide at the wide end, 11cm thick",
          condition="leatherette worn through at the corners, one loose latch, the velvet hollow shiny from long use with a faint dusting of white rosin powder"),
  notes="3-33 전당포 창고에서 나오는 '바이올린 케이스'는 이 케이스가 아니라 맡긴 바이올린이 든 별도 케이스(pawned_violin_case)로 봄",
  states=[
    S("empty_violin_case__s1_spilled", "계단에서 뒤집혀 열림(1-6)", ["1-6"], "잠금쇠가 풀려 뚜껑이 벌어지고 악보·사탕이 쏟아짐. 안은 비어 있음"),
    S("empty_violin_case__s2_carried", "들고 다니는 모습(닫힘)", R("1-7", "1-8", "2-1", "2-9"), "가슴에 안고 다님. 1-8 열어 사탕을 나눠 줌",
      shape="the same shaped black violin case closed, two metal latches and a leather handle", condition="leatherette worn through at the corners, one loose latch"),
    S("empty_violin_case__s3_pawnshop", "전당포 진열장 위 — 전당표를 악보 사이에", ["2-8"], "부감: 붉은 벨벳 위에 악보와 사탕 봉지, 악보 사이에서 전당표를 꺼냄"),
    S("empty_violin_case__s4_workshop", "공방 작업대 위 열린 케이스(3-10)", ["3-10"], "열린 케이스 안 악보와 사탕뿐. 선영의 고백"),
  ]),

P("manseok_clarinet", "만석의 클라리넷", "A",
  R("3-3", "3-33", "3-34"),
  aliases=["클라리넷", "만석의 클라리넷", "클라리넷 케이스"],
  era="1970년대 극장 악단(회상) / 1988 전당포 / 2003",
  material="B♭ 클라리넷: 검은 목재(그라나디야) 관, 은빛 니켈 키, 패드. 검은 하드케이스",
  size="조립 길이 66cm(마우스피스 포함, 배럴~벨 60cm), 관 지름 약 3cm, 벨 지름 7cm. 케이스 38×20×8cm",
  colors=["#1C1A1A", "#C8CCD0", "#4A3A30", "#2B2B30"],
  condition="회상: 반짝. 전당포: 케이스에 먼지가 소복. 에필로그: 곽 영감이 고쳐 새로 맞춘 패드, 반들반들한 키",
  shape="5마디(마우스피스·배럴·윗관·아랫관·벨)로 된 검은 클라리넷, 은빛 키와 고리. 케이스는 직사각 하드케이스, 안에 분해한 관이 칸마다 누움",
  role="만석의 과거(극장 쇼 악단), 아내와의 만남. 약값 때문에 전당포에 맡김 → 섬 아이들이 '찾을 돈'으로 되찾음(3-33) → 2003 은주와 이중주(3-34). 3-3·3-21에선 보이지 않는 클라리넷을 쥐는 손가락",
  ref="https://emuseum.nmmusd.org/objects/17821/clarinet-bflat (미국 국립음악박물관, 검색 요약). 1970년대 한국 쇼단·케이스는 미확인",
  en=dict(name="a B-flat clarinet", shape="a black clarinet in five sections with silver keys and rings, shown assembled and beside its open rectangular hard case with the parts lying in fitted slots",
          material="black wood, nickel-silver keys", size="66cm long assembled", condition="well kept"),
  offscreen="3-21(객석의 만석, 보이지 않는 클라리넷 구멍을 막는 손가락 — 악기는 없음)",
  states=[
    S("manseok_clarinet__s1_1970s", "회상 — 1970년대 극장 쇼 악단", ["3-3"], "세피아 회상. 젊은 만석의 긴 손가락이 구멍을 막았다 엶. 새 악기처럼 반짝",
      condition="bright and new, glossy black wood, shining keys", era="1970s Seoul"),
    S("manseok_clarinet__s2_pawned_case", "전당포 창고 — 먼지 쌓인 클라리넷 케이스", ["3-33"], "창고 구석에서 바이올린 케이스와 나란히 나옴. 먼지를 후 불어 턺",
      name="a dusty black clarinet hard case", shape="a closed rectangular black hard case with two latches and a small handle",
      material="black leatherette over wood, metal latches", size="38 by 20 by 8cm", condition="a thick layer of gray dust on top, one corner scuffed", era="1988 Seoul",
      colors=["#2B2B30", "#9A9690", "#C8CCD0"]),
    S("manseok_clarinet__s3_epilogue", "15년 뒤 — 새로 맞춘 패드, 반들반들한 키(2003)", ["3-34"], "곽 영감이 고친 클라리넷. 키가 반들반들, 새 패드(밝은 크림색)",
      condition="restored: fresh cream-white pads, polished gleaming keys, the old black wood oiled", era="2003 Seoul",
      colors=["#1C1A1A", "#E6E9EC", "#EFE6D2", "#2B2B30"]),
  ]),

P("pawn_ticket_manseok", "만석의 전당표", "A",
  R("2-8", "3-3", "3-29"),
  aliases=["전당표", "만석의 전당표", "누렇게 바랜 전당표"],
  material="얇은 갱지 인쇄 양식(칸 인쇄 + 손글씨), 빨간 인주 도장",
  size="펼쳐서 가로 12cm·세로 18cm, 네 번 접어 6×9cm",
  colors=["#D9C79A", "#F1E9D2", "#B0302A", "#5A4A3A"],
  condition="누렇게 바램. 접힌 자리가 하얗게 닳아 보풀이 일고, 맡긴 물건 이름 칸이 그 접힌 자리에 걸려 반쯤 지워져 읽을 수 없음. 귀퉁이 말림",
  shape="세로로 긴 양식지, 위에 가게 이름 자리(글자 없이 굵은 줄), 아래로 칸 4~5줄(물건·금액·기한 자리 — 글자 대신 흐린 선), 오른쪽 아래 빨간 네모 도장. 네 번 접은 자국",
  role="만석이 아내 약값으로 클라리넷을 맡긴 증표. 기한 지남(2-8). 3-3 은주에게 처음 고백. 3-29 주머니 속에서 쥐었다 놓음",
  ref="미확인(전당표 양식 자료 없음 — 1987년 전당포 2,350곳만 확인, props.md 고증 출처 표)",
  en=dict(name="an old pawn ticket", shape="a small printed form slip with a heavy blank title bar, four or five ruled rows filled with faint illegible handwriting marks, a red square seal stamp in the lower right corner, folded in four",
          material="thin newsprint-like paper, red seal ink", size="12 by 18cm unfolded", condition="yellowed with age, the fold lines worn white and fuzzy, one row rubbed half away along a fold, curled corners"),
  notes="글자는 식자 단계에서('만복전당포'). 이미지엔 글자 없이",
  states=[S("pawn_ticket_manseok__s1", "닳은 전당표", R("2-8", "3-3", "3-29"), "변화 없음. 2-8 엄지가 날짜를 문지름, 3-29 주머니 속")]),

P("choi_handkerchief", "최 계장의 손수건", "A",
  R("1-16", "2-6", "2-7", "2-15", "3-12", "3-13", "3-14", "3-20", "3-23", "3-26", "3-29", "3-32", "3-34"),
  aliases=["손수건", "최 계장 손수건", "흰 손수건"],
  era="1987~88 서울(에필로그 2003)",
  material="얇은 흰 면 손수건",
  size="40×40cm 정사각, 가장자리 접어 박음질 폭 0.5cm",
  colors=["#F4F2EC", "#DCD8CE", "#C8C2B4"],
  condition="깨끗이 다린 흰 면. 축축할 땐 구김이 지고 반투명하게 처짐",
  shape="무늬 없는 흰 정사각 손수건. 평소엔 네 번 접어 손에 쥠",
  role="최 계장의 땀=진지함. 압정을 닦아 줌(1-16, 얼굴 대신 손), 말라 있음(2-7, 걸음을 멈춘 날), 땀으로 젖음(2-15·3-12), 짜서 화분에 똑똑(3-13), 얼굴을 덮음(3-26), 에필로그에 미리 쥠(3-34)",
  ref="미확인",
  en=dict(name="a plain white cotton handkerchief", shape="a square handkerchief with a narrow stitched hem, shown flat, folded in four and crumpled in a hand",
          material="thin white cotton", size="40 by 40cm", condition="clean and ironed"),
  states=[
    S("choi_handkerchief__s1_dry", "마른 손수건", R("1-16", "2-6", "2-7", "3-14", "3-29", "3-32", "3-34"), "다린 흰 면. 2-7 '말라 있다'(극접사)"),
    S("choi_handkerchief__s2_damp", "땀에 젖은 손수건", R("2-15", "3-12", "3-13", "3-20", "3-23", "3-26"),
      "축축해 구김지고 처짐. 3-13 두 손으로 짜 물방울이 떨어짐. 3-26 얼굴을 덮음",
      condition="damp with sweat, limp, wrinkled and slightly translucent, a few drops falling when wrung"),
  ]),

P("sunrye_ladle", "순례 할머니의 국자", "A",
  R("1-8", "1-11", "1-12", "1-14", "2-1", "2-10", "3-6", "3-14", "3-21", "3-25", "3-29"),
  aliases=["국자", "순례 할머니 국자"],
  material="스테인리스(또는 양은) 국자, 긴 손잡이 끝에 걸이 고리",
  size="전체 길이 38cm, 국자 머리 지름 10cm·깊이 5cm",
  colors=["#BFC4C6", "#8E9396", "#6A5A48"],
  condition="오래 써서 머리 테두리가 살짝 찌그러짐(솥을 쳐서), 손잡이에 손때, 바닥에 그을음",
  shape="둥근 반구형 국자 머리, 길고 납작한 손잡이가 머리에서 위로 휘어 올라감, 끝에 걸이 구멍",
  role="섬의 신호: 솥을 '탕탕'(웃음을 잠재움 1-8), '탕, 탕, 탕' 세 번 = 국밥 다 됐다(3-6). 덕수가 빌려 뚱보 테두리를 침(3-6·3-21·3-25) — 「섬의 하루」 '저녁'. 3-29 버스 앞에서 흔듦",
  ref="미확인(웹 검색으로 치수 자료를 찾지 못함)",
  en=dict(name="a long-handled soup ladle", shape="a round deep ladle bowl with a long flat handle curving up and ending in a hanging hole",
          material="stainless steel", size="38cm long, bowl 10cm across", condition="the bowl rim slightly dented from striking a pot, handle polished by use, soot under the bowl"),
  states=[
    S("sunrye_ladle__s1", "할머니 손의 국자", R("1-8", "1-11", "1-12", "1-14", "2-1", "2-10", "3-6", "3-14", "3-29"), "솥 가장자리를 탕탕"),
    S("sunrye_ladle__s2_borrowed", "덕수가 빌려 간 국자(악기)", R("3-6", "3-21", "3-25"), "같은 국자. 덕수가 뚱보 테두리를 침"),
  ]),

P("soup_pot", "국솥(국밥집 무쇠 솥)", "A",
  R("1-8", "1-14", "2-1", "3-6", "3-14", "3-21"),
  aliases=["국솥", "솥", "무쇠 솥"],
  material="무쇠 가마솥, 두꺼운 나무 뚜껑",
  size="솥 지름 70cm·깊이 40cm, 솥전(날개) 폭 6cm",
  colors=["#2E2B28", "#5A534C", "#A07A50", "#E8E2D6"],
  condition="검은 무쇠, 솥전 가장자리가 국자로 쳐서 반질, 겉에 그을음, 김이 늘 오름",
  shape="둥근 바닥 무쇠 솥, 몸통 위쪽에 둘러진 넓은 솥전(날개), 연탄 화덕 위에 걸림. 나무 판자 두 쪽을 잇댄 뚜껑과 손잡이",
  role="천막의 중심. 국자 신호의 북(탕탕·탕, 탕, 탕), 지휘봉 퐁당(2-1)",
  ref="미확인(웹 검색으로 치수 자료를 찾지 못함)",
  en=dict(name="a huge cast-iron soup cauldron", shape="a round-bottomed iron cauldron with a wide flange rim around its upper body, sitting on a coal stove, a wooden plank lid with a handle beside it, steam rising",
          material="black cast iron, wooden lid", size="70cm across, 40cm deep", condition="sooty outside, the flange rim polished where the ladle strikes it"),
  states=[S("soup_pot__s1", "김이 오르는 솥", R("1-8", "1-14", "2-1", "3-6", "3-14", "3-21"), "변화 없음. 3-21은 겹침(해 질 녘 천막)")]),

P("mija_savings_can", "미자의 '찾을 돈' 깡통", "A",
  R("3-11", "3-33"),
  aliases=["찾을 돈 깡통", "찾을 돈", "미자의 깡통"],
  material="빈 분유 깡통(양철, 상표 종이 벗김), 굵은 검은 유성펜 글씨",
  size="지름 13cm·높이 17cm",
  colors=["#BFC3C5", "#1E1E1E", "#8E4B2A", "#C9A64A"],
  condition="뚜껑 없이 위가 열림, 안쪽 테두리에 따개로 잘린 톱니 자국. 옆면에 굵은 펜 글씨(식자 단계) 둘레에 펜이 번진 자국. 바닥 테두리 녹 점",
  shape="세워 둔 원통 깡통. 옆면 가운데 손글씨 자리(이미지에선 굵은 펜으로 그린 빈 테두리만). 3-11 바닥에 동전 하나, 3-33 동전 가득",
  role="미자가 고물 판 돈을 모아 선영의 바이올린과 만석의 클라리넷을 되찾는 돈(3-33). 동그리와 같은 분유 깡통 — 섬의 깡통이 악기를 되찾는다",
  ref="미확인",
  en=dict(name="a tin can used as a savings box", shape="an upright cylindrical milk-powder tin can with no lid, a rough rectangular frame drawn with thick black marker on its side left blank for lettering added in editing",
          material="tinplate, black marker ink", size="13cm diameter, 17cm tall", condition="label peeled off, jagged can-opener cut around the inside of the top rim, rust dots on the bottom rim"),
  notes="'찾을 돈' 글씨는 식자 단계",
  states=[
    S("mija_savings_can__s1_first_coin", "첫 동전(3-11)", ["3-11"], "깡통 속에 동전 하나(부감)",
      shape="an upright cylindrical tin can with no lid seen from above with a single coin at the bottom, a blank marker-drawn frame on its side for lettering added in editing"),
    S("mija_savings_can__s2_full", "가득 — 계산대 위로 뒤집음(3-33)", ["3-33"], "고물 판 동전이 가득, 뒤집어 와르르 쏟음",
      shape="the same open tin can tipped upside down, a stream of many small plain coins pouring out, a blank marker-drawn frame on its side for lettering added in editing", era="1988 Seoul"),
  ]),

P("taejun_violin", "태준의 바이올린", "A",
  R("2-4", "3-18", "3-22", "3-24"),
  aliases=["태준 바이올린"],
  material="가문비 앞판·불꽃무늬 단풍 뒤판, 붉은 갈색 니스, 흑단 부속",
  size="4/4: 전체 59cm, 몸통 35.5cm",
  colors=["#A0451F", "#D27A3A", "#1E1A18", "#E8E2D6"],
  condition="흠 하나 없이 반짝, 지판 아래 송진 가루를 헝겊으로 닦음",
  shape="정통 고급 바이올린. 곽 영감 바이올린(꿀 빛)과 구분: 더 붉은 오렌지 갈색 니스, 뒤판 불꽃무늬가 또렷",
  role="'진짜 음악'의 얼굴. 2-4 라 줄을 버릇처럼 튕김('팅', 일부러 높게 맞춤). 3-18 악장 연주",
  ref="미확인",
  en=dict(name="an expensive full-size violin", shape="a classic violin with scroll, four strings, two f-holes, a strongly flamed maple back",
          material="spruce, flamed maple, ebony fittings", size="59cm long", condition="flawless glossy reddish-orange varnish, a trace of white rosin dust under the strings"),
  states=[S("taejun_violin__s1", "변화 없음", R("2-4", "3-18", "3-22", "3-24"), "3-22·3-24는 케이스 안(뚜껑 열고 닫음)")]),

P("taejun_spare_e_string", "태준의 여분 E현", "A",
  R("3-22", "3-24", "3-25", "3-28"),
  aliases=["여분 E현", "새 E현", "새 줄", "E현"],
  material="바이올린 E현(강철 단선, 끝에 작은 볼 또는 고리)",
  size="펼치면 약 60cm, 지름 6cm 원으로 동그랗게 감김, 굵기 0.026cm(0.26mm)",
  colors=["#E4E8EC", "#B8BEC4", "#C9A24A"],
  condition="새것, 은빛 반짝",
  shape="가는 은색 강철 줄 한 가닥이 작은 동그라미로 몇 겹 감겨 있음, 한쪽 끝에 작은 금색 볼(줄걸이용)",
  role="태준이 은주의 귀를 알아보고 건네는 줄(3-22 'E현. 1번 줄.'). 곽 영감이 1분 안에 감음(3-24). 3-28 '그건 가져' — 동그리에 새 E현이 혼자 반짝",
  ref="https://collection.tamuseum.org.nz/objects/19117/paper-pocket-for-violin-string (예비 줄 포장, 검색 요약)",
  en=dict(name="a new violin E string coiled in a small ring", shape="one thin silver steel string wound in a few loops into a small circle, a tiny gold ball end at one end",
          material="steel wire, brass ball end", size="coil 6cm across, about 60cm long unwound", condition="brand new and bright"),
  states=[
    S("taejun_spare_e_string__s1_coiled", "동그랗게 감긴 새 줄(건넴)", ["3-22"], "두 손 사이를 건너가는 줄(극접사)"),
    S("taejun_spare_e_string__s2_on_dongguri", "동그리에 걸린 새 E현", R("3-24", "3-25", "3-28"), "dongguri__s8_new_e 참고",
      shape="the new silver string now stretched on the homemade tin-can violin beside three older duller strings"),
  ]),

P("red_neckerchief", "빨간 손수건(본선 목 스카프)", "A",
  NECK,
  aliases=["빨간 손수건", "빨간 스카프", "빨간 천"],
  material="빨간 무명(면) 천을 잘라 만든 삼각 천, 가장자리 손바느질 감침",
  size="삼각형 밑변 50cm·높이 25cm, 목에 매면 앞으로 늘어진 끝 10cm",
  colors=["#B8282E", "#8E1E24", "#D9474A"],
  condition="새로 잘라 만든 것. 가장자리 감침질 바늘땀이 고르지 않게 보임(할머니 손바느질), 같은 천에서 잘라 아이들 것이 모두 같은 색",
  shape="작은 삼각 천을 접어 목에 두르고 앞에서 한 번 묶은 작은 목 스카프. 매듭 아래로 두 끝이 짧게 늘어짐",
  role="순례 할머니가 빨간 천을 잘라 만든 섬 단원의 표시(G7 확정). 다솜중의 검은 연주복과 대비되는 섬 아이들의 한 색. 동민·미자·덕수·섬 아이 6명(은주·선영은 안 맴)",
  ref="미확인(G7 확정 설정)",
  en=dict(name="a small red cloth neckerchief", shape="a small triangle of red cotton folded and tied at the front of the neck with one knot, two short ends hanging below the knot, shown flat and tied",
          material="red cotton cloth, hand-stitched hem", size="triangle 50cm across, 25cm deep", condition="newly cut, slightly uneven hand-whipped stitches along the edges"),
  notes="outfits_en.json 'a small red cloth neckerchief tied at the neck'과 같은 물건. 착용: dongmin·mija·deoksu·섬 아이 6명(characters.json)",
  states=[
    S("red_neckerchief__s1_flat", "펼친 천(만든 그대로)", NECK[:1], "화면에 펼친 모습은 나오지 않음 — 맨 모습을 그리기 전 콘티 참고용 시트(씬 칸은 첫 착용 씬)", shape="a small triangle of red cotton laid flat, hand-whipped hem visible"),
    S("red_neckerchief__s2_tied", "목에 맨 모습", NECK, "아이들 목에 매어 앞에서 한 번 묶음"),
  ]),

P("newspaper_seoulmaeil", "신문 「한강신보」 사회면 단신", "A",
  R("2-20", "2-21", "3-10", "3-19"),
  aliases=["한강신보", "신문", "쓰레기 밴드 기사", "「한강신보」"],
  material="신문 용지(갱지), 검은 잉크 인쇄",
  size="대판 한 면 39×54cm(한 번 접어 39×27cm), 단신 기사는 손바닥만 함(8×10cm)",
  colors=["#E6E0D0", "#2A2A2A", "#9A968C"],
  condition="2-20 펼침 → 기사가 위로 오게 접힘 → 2-21 손가락에 힘이 들어가 구겨짐. 회상(3-10·3-19)에선 제목만 극접사",
  shape="1987년식 세로쓰기 지면: 위아래로 흐르는 좁은 세로 글줄이 여러 단, 맨 아래 구석에 작은 네모 기사(굵은 세로 제목 줄 + 세로 본문 몇 줄). 글자는 그리지 않고 회색 줄로",
  role="'쓰레기 밴드' — 은주를 무너뜨리는 말. 만석이 딸이 계속했다는 걸 앎(2-21). 본선에서 다시 귀를 막음(3-19)",
  ref="https://www.seoul.co.kr/news/1996/10/01/19961001003001 (1987~88 일간지 세로쓰기), https://www.journalist.or.kr/m/m_article.html?no=48168 (대판 39×54cm, 검색 요약). 사회면 단 수·종이 색은 미확인",
  en=dict(name="a folded daily newspaper page with a tiny article in the bottom corner",
          shape="a 1980s Korean broadsheet page laid out in vertical writing: many narrow blocks of short vertical gray text lines running top to bottom, a small boxed brief article in the bottom corner with a bold vertical headline bar, all lettering rendered as illegible gray lines",
          material="newsprint, black ink", size="39 by 54cm page, the brief about 8 by 10cm", condition="slightly yellowed newsprint"),
  notes="제호·제목·본문 글자는 식자 단계. 가공 신문",
  states=[
    S("newspaper_seoulmaeil__s1_open", "평상에 펼친 신문", ["2-20"], "집하장 아저씨가 펼쳐 손가락으로 짚음"),
    S("newspaper_seoulmaeil__s2_folded", "기사가 위로 오게 접힌 신문", R("2-20", "2-21"), "순례 할머니가 접어 평상 끝에. 2-21 만석의 손가락에 구겨짐",
      shape="the newspaper folded so the small corner article faces up, vertical gray text lines, no readable letters", condition="creased, one corner crumpled by a gripping hand"),
    S("newspaper_seoulmaeil__s3_flash", "회상 극접사 — 단신 제목", R("3-10", "3-19"), "제목 줄만 화면 가득(글자는 식자)",
      shape="an extreme close-up of a small newspaper brief in vertical layout, a bold blank vertical headline bar beside a few vertical gray text lines"),
  ]),

P("contest_poster", "전국 청소년 합주제 공고(금빛 테두리 종이)", "A",
  R("1-14", "1-15", "1-16", "1-17"),
  aliases=["합주제 공고", "금빛 테두리 종이", "대회 공고"],
  material="흰 모조지 인쇄 포스터, 금색 테두리 인쇄",
  size="A3(29.7×42cm)",
  colors=["#F4EFE2", "#C9A23A", "#2B2B2B", "#B03A2E"],
  condition="교회 게시판에서 얻어 와 둘둘 말렸던 자국(가로 물결), 네 귀퉁이 압정 구멍",
  shape="세로 직사각 종이. 둘레에 폭 1.5cm 금색 이중 테두리. 가운데 굵은 제목 줄과 본문 몇 줄(글자 대신 선). 위쪽 가운데 작은 음표 장식(추측)",
  role="꿈의 종이. 선영이 펼침(1-14), 게시판에 압정 넷(1-15), 정리 예정 알림과 나란히(1-17 '두 장의 종이')",
  ref="미확인",
  en=dict(name="a contest notice poster with a gold border", shape="a portrait sheet with a double gold printed border, a bold blank title bar and several lines of illegible text marks, a small musical-note ornament at the top",
          material="white printed paper, gold ink", size="A3, 29.7 by 42cm", condition="wavy from having been rolled up, pin holes at the four corners"),
  notes="1-17 Insert 글: '전국 청소년 합주제. 국민학교·중학교 학생 합주단. 자유곡 1곡. 예선 1988년 4월.' — 식자",
  states=[
    S("contest_poster__s1_rolled", "둘둘 말린 종이를 폄(1-14)", ["1-14"], "천막 그늘 속 금빛 테두리 반짝",
      shape="the poster half unrolled in two hands, curling at the ends, gold border catching the light"),
    S("contest_poster__s2_pinned", "게시판에 압정 네 개", R("1-15", "1-16", "1-17"), "네 귀퉁이 압정. 1-17 강바람에 떨림(사락)",
      shape="the poster pinned flat with four thumbtacks at its corners, a bold blank title bar and illegible text marks inside a double gold border"),
  ]),

P("clearance_notice_1987", "갈대섬 정리 예정 알림(회색 갱지)", "A",
  R("1-16", "1-17"),
  aliases=["정리 예정 알림", "회색 갱지", "공문"],
  material="회색 갱지, 등사·타자 인쇄, 빨간 관인(네모 도장)",
  size="19×26cm(1980년대 공문 용지, B5급)",
  colors=["#C9C6BC", "#2B2B2B", "#C0302A"],
  condition="얇은 갱지라 바람에 바스락, 네 귀퉁이 압정(하나는 진흙에서 주워 손수건으로 닦은 것)",
  shape="세로 종이, 가로쓰기: 위에 제목 줄, 본문 가로줄 여러 개(글자 대신 선), 아래 발신 기관 자리 끝 글자에 빨간 네모 관인이 걸쳐 찍힘(1986.12 이후 양식, 성명 없음)",
  role="'정리할 예정입니다' — 은주가 아는 '정리'(쓸 것과 버릴 것). 금빛 테두리 종이와 같은 크기로 사락·바스락(1-17)",
  ref="https://theme.archives.go.kr/next/officialDocument/docSketch02.do?page=2 (국가기록원: 가로쓰기, 19×26cm 안팎 용지, 관인 위치). 관인 크기는 미확인",
  en=dict(name="a gray official notice sheet with a red seal", shape="a portrait sheet of thin gray paper written horizontally: a blank title line and rows of illegible horizontal typed text marks, a red square official seal stamped over the last character of the issuing office name near the bottom",
          material="thin gray newsprint paper, red seal ink", size="19 by 26cm", condition="thin and crackly, pinned at four corners"),
  notes="1-17 Insert 글은 식자",
  states=[S("clearance_notice_1987__s1", "게시판에 붙은 알림", R("1-16", "1-17"), "1-17 빨간 도장 극접사")]),

P("contest_leaflet", "합주제 참가 설명회 안내문(전단)", "A",
  R("2-3", "2-4"),
  aliases=["안내문", "합주제 전단", "참가 설명회 안내문"],
  material="얇은 모조지 1도 인쇄 전단",
  size="B5(18.2×25.7cm)",
  colors=["#F2EEE4", "#2B2B2B", "#C9A23A"],
  condition="선영 무릎 위에서 반으로 접힌 자국, 2-4 다른 학교 아이가 부채질",
  shape="세로 전단 한 장, 위에 제목 줄, 아래 일시·장소 줄(글자 대신 선), 맨 위 가는 금색 띠(공고와 같은 디자인 계열)",
  role="섬 아이들을 '진짜 음악' 앞으로 데려가는 종이(2-3), 연습실의 더운 공기(2-4 부채질 — 아무도 춥지 않다)",
  ref="미확인",
  en=dict(name="a one-page event leaflet", shape="a single portrait sheet with a thin gold band at the top, a blank title bar and lines of illegible text marks",
          material="thin printed paper", size="18.2 by 25.7cm", condition="folded in half once, slightly creased"),
  states=[S("contest_leaflet__s1", "안내문", R("2-3", "2-4"), "2-3 무릎 위 Insert(글자 식자), 2-4 부채")]),

P("award_certificate", "대상 상장", "A",
  ["3-28"],
  aliases=["상장"],
  material="두꺼운 미색 상장 용지, 금박 테두리 무늬 인쇄",
  size="B4 가로 놓임(36.4×25.7cm)",
  colors=["#F3ECD8", "#C9A23A", "#2B2B2B", "#B0302A"],
  condition="새것, 아이들이 돌려 보느라 귀퉁이 하나가 살짝 꺾임",
  shape="가로로 긴 상장. 둘레에 금색 덩굴 무늬 테두리(문양은 단순 기하 덩굴, 국가 문장 아님), 가운데 큰 제목 줄과 본문 줄, 아래 빨간 네모 도장",
  role="섬 아이들의 대상. 로비에서 돌려 봄(3-28)",
  ref="미확인(1980년대 상장 양식 자료 없음)",
  en=dict(name="an award certificate", shape="a landscape certificate with an ornate gold vine-pattern border, a large blank title bar and illegible text lines, a red square seal at the bottom",
          material="thick cream paper, gold foil print", size="36.4 by 25.7cm", condition="new, one corner slightly bent"),
  states=[S("award_certificate__s1", "새 상장", ["3-28"], "변화 없음")]),
]
