# (씬, Insert 줄에 들어 있는 글, [소품 id] 또는 "NONPROP:사유")
IMAP = [
("1-2", "구리 파이프 토막", ["copper_pipe_piece"]),
("1-3", "나무 몸통 하나", ["broken_violin_body"]),
("1-3", "영감의 굽은 손가락", ["broken_violin_body"]),
("1-5", "트랜지스터라디오", ["mother_radio"]),
("1-5", "은색 소리굽쇠", ["tuning_fork_necklace"]),
("1-5", "합판 벽, 은주의 손가락", ["plywood_wall"]),
("1-5", "동민의 작은 주먹", ["plywood_wall"]),
("1-6", "붉은 벨벳", ["empty_violin_case", "sheet_music", "candy"]),
("1-6", "분필 끝", ["chalk"]),
("1-11", "커다란 분유 깡통", ["dongguri"]),
("1-11", "구부린 포크 줄받침", ["dongguri", "kwak_old_bow"]),
("1-12", "비눗물 대야", ["xray_film_line", "bone_drum"]),
("1-14", "숟가락 자루를 매끈하게", ["baton"]),
("1-17", "금빛 테두리 종이", ["contest_poster"]),
("1-17", "회색 갱지", ["clearance_notice_1987"]),
("1-17", "빨간 도장, 극접사", ["clearance_notice_1987"]),
("1-17", "빨간 직인", ["clearance_notice_1987"]),
("1-17", "목장갑 낀 손", ["cotton_work_gloves", "scrap_sack"]),
("2-3", "안내문", ["contest_leaflet"]),
("2-4", "소리굽쇠를 무릎에", ["tuning_fork_necklace"]),
("2-5", "가구 조사표", ["survey_form", "choi_envelope"]),
("2-6", "뚱보에 활을", ["ttungbo"]),
("2-7", "수첩", ["choi_memo"]),
("2-8", "전당표", ["pawn_ticket_manseok"]),
("2-9", "야전상의 소매", ["manseok_field_jacket"]),
("2-15", "섬 어귀 게시판", ["notice_board", "notice_1988_jan"]),
("2-20", "한강신보", ["newspaper_seoulmaeil"]),
("2-21", "기사 위의 긴 손가락", ["newspaper_seoulmaeil"]),
("2-25", "은색 소리굽쇠", ["tuning_fork_necklace", "mother_radio", "radio_box"]),
("3-1", "사과 상자", ["apple_crate", "glue_brush", "bulb", "workbench"]),
("3-3", "전당표", ["pawn_ticket_manseok"]),
("3-4", "공책", ["composition_notebook"]),
("3-10", "오선지", ["staff_paper"]),
("3-10", "한강신보", ["newspaper_seoulmaeil"]),
("3-10", "만복전당포", "NONPROP:두 사람 어깨가 스치는 회상(2-8 장소 회상, 소품 없음)"),
("3-11", "찾을 돈", ["mija_savings_can"]),
("3-12", "표지", ["report_cover"]),
("3-12", "본문", ["report_cover"]),
("3-12", "구두 끝", ["choi_shoes"]),
("3-12", "양철 지붕", ["tin_roof_1950s"]),
("3-18", "빛바랜 줄 봉투", ["empty_string_envelope", "workbench"]),
("3-19", "한강신보", ["newspaper_seoulmaeil"]),
("3-19", "은주의 손가락 마디", ["plywood_wall"]),
("3-19", "어른 여자의 손", ["plywood_wall"]),
("3-20", "구두 끝", ["choi_shoes"]),
("3-20", "트럭 불빛", ["dawn_truck"]),
("3-20", "목장갑 낀 손들", ["cotton_work_gloves", "scrap_sack", "hanging_scale"]),
("3-20", "찢어진 비닐", ["white_vinyl"]),
("3-20", "빨간 깃발", ["red_rag_flag"]),
("3-21", "국솥을 국자로", ["soup_pot", "sunrye_ladle", "soup_tent"]),
("3-21", "라디오 수리점", ["radio_repair_shop_radios", "tuning_fork_necklace"]),
("3-21", "비닐 한 장", ["white_vinyl"]),
("3-25", "별 하나", "NONPROP:밤하늘 별(배경)"),
("3-26", "리어카 손잡이", ["handcart"]),
("3-29", "전당표", ["pawn_ticket_manseok"]),
("3-34", "이불을 둘둘", ["blanket"]),
]
