# scene_presets props 항목 → 소품 id. list = 모두 그 씬에 있어야 함, tuple = 하나만 있으면 됨, str = 소품 아님(사유)
# 키 앞 '=' 는 항목 전체가 정확히 같을 때만
INST4 = ["dongguri", "ttungbo", "kkwaekkwaegi", "bone_drum"]
ALL = INST4 + ["can_violin_2", "can_violin_3", "pot_lid_cymbals", "bottle_xylophone"]
PMAP = [
("빈 자루", ["scrap_sack"]), ("고물 자루", ["scrap_sack"]), ("갈고리", ["iron_hook"]),
("비누 공장 트럭", ["soap_truck"]), ("철공소 트럭", ["ironworks_truck"]), ("빨간 헝겊 깃발", ["red_rag_flag"]),
("노란 칠한 쇳덩이", ["yellow_painted_iron"]), ("구리 파이프 토막", ["copper_pipe_piece"]), ("짧은 쇠막대", ["iron_rod"]),
("쇠막대", ["iron_rod"]), ("누룽지", ["nurungji"]), ("구리 토막", ["copper_pipe_piece"]), ("매다는 저울", ["hanging_scale"]),
("걸이 저울", ["hanging_scale"]), ("병뚜껑", ["bottle_caps"]), ("목 부러진 바이올린", ["broken_violin_body"]),
("부드러운 천", ["polishing_cloth"]), ("지폐", ["scrap_money"]), ("동전", ["scrap_money"]), ("톱밥", ["sawdust"]),
("석유곤로", ["kerosene_stove"]), ("밥상", ["low_table"]), ("김치찌개", ["kimchi_jjigae"]), ("된장찌개", ["doenjang_jjigae"]),
("목수건", ["neck_towel"]), ("문고리", ["shack_door"]), ("공구 자루", ["tool_sack"]), ("리어카", ["handcart"]),
("엄마", ["mother_radio"]), ("라디오와 상자", ["radio_box"]), ("나무 상자", ["radio_box"]), ("소리굽쇠", ["tuning_fork_necklace"]),
("이불", ["blanket"]), ("합판 벽", ["plywood_wall"]), ("빈 바이올린 케이스", ["empty_violin_case"]), ("악보", ["sheet_music"]),
("사탕", ["candy"]), ("버스 토큰", ["bus_token"]), ("분필", ["chalk"]), ("받아쓰기 공책", ["dictation_notebook"]),
("선영 구두", ["seonyoung_shoes"]), ("검정 고무장화", ["big_black_boots"]), ("=고무장화", ["rubber_boots"]),
("국솥", ["soup_pot"]), ("국자", ["sunrye_ladle"]), ("평상", ["pyeongsang"]), ("사포", ["sandpaper"]),
("나뭇조각", ["kwak_wood_piece"]), ("다락", ["ladder_attic"]), ("고물상 불빛", ["tin_roof"]),
("동그리", ["dongguri"]), ("공장 시절 낡은 활", ["kwak_old_bow"]), ("동그리와 활", ["kwak_old_bow"]), ("동그리·활", ["kwak_old_bow"]),
("싸 온 천", ["wrap_cloth"]), ("싼 천", ["wrap_cloth"]), ("뚱보", ["ttungbo"]), ("기름통", ["ttungbo"]), ("배수관", ["kkwaekkwaegi"]),
("페인트 통", ["bone_drum"]), ("뼈다귀 북", ["bone_drum"]), ("나무 숟가락 북채", ["drumstick_spoons"]), ("꽥꽥이", ["kkwaekkwaegi"]),
("비눗물 대야", ["xray_film_line", "bone_drum"]), ("나사못", ["workbench_screws"]), ("까마귀", "동물(가공 연출, 소품 아님)"),
("고물상 벽 달력", ["calendar_junkshop"]), ("천막 기둥 달력", ["calendar_tent"]), ("악기 넷", INST4), ("모든 악기", ALL), ("모든 섬 악기", ALL),
("분유 깡통 세 대", ["dongguri", "can_violin_2", "can_violin_3"]), ("냄비 뚜껑", ["pot_lid_cymbals"]), ("빈 병", ["bottle_xylophone"]),
("병 실로폰", ["bottle_xylophone"]), ("깡통 바이올린 2호", ["can_violin_2"]), ("깡통 바이올린 2·3호", ["can_violin_2", "can_violin_3"]),
("3호", ["can_violin_3"]), ("=나무 숟가락 목", ("can_violin_2", "can_violin_3")),
("지휘봉", ["baton"]), ("합주제 공고", ["contest_poster"]), ("금빛 테두리 공고", ["contest_poster"]), ("압정", ["thumbtacks"]),
("회색 갱지", ["clearance_notice_1987"]), ("새 공문", ["notice_1988_jan"]), ("공문(천막 기둥", ["relocation_notice"]),
("게시판", ["notice_board"]), ("누런 서류 봉투", ["choi_envelope"]), ("서류 봉투", ["choi_envelope"]), ("=서류", ["choi_envelope"]),
("손수건", ["choi_handkerchief"]), ("목장갑 손", ["cotton_work_gloves"]), ("부서진 피아노", ["broken_piano"]), ("굵은 쇠줄", ["piano_wire"]),
("피아노 쇠줄", ["piano_wire"]), ("흔들리는 전구", ["bulb"]), ("안내문", ["contest_leaflet"]),
("태준 바이올린과", ["taejun_violin"]), ("태준", ["taejun_case"]), ("=헝겊", ["taejun_rag"]), ("올림픽 포스터", ["olympic_poster"]),
("가구 조사표", ["survey_form"]), ("진흙 묻은 구두", ["choi_shoes"]), ("진흙 위 고인 물", "지면(배경)"), ("수첩", ["choi_memo"]),
("볼펜", ["ballpoint_pen"]), ("만복전당포 간판", ["pawnshop_sign"]), ("문 위의 종", ["door_bell"]), ("문 종", ["door_bell"]),
("선영 전당표", ["pawn_ticket_seonyoung"]), ("전당표", ["pawn_ticket_manseok"]), ("=도장", ("pawn_stamp", "office_stamp")),
("주판", ["abacus"]), ("전파사 진열대 라디오", ["electronics_shop_radio"]), ("쓰레기 더미", ["trash_mound_wet"]),
("깡통 더미", ["trash_mound_wet"]), ("손전등", ["flashlight"]), ("막대기", ["mija_stick"]), ("판자로 막은 작은 공방", "장소(공방, sets.md)"),
("연탄난로", ["coal_stove_kettle"]), ("굴러다니는 깡통", ["kicked_can"]), ("연탄 화덕", ["coal_brazier"]),
("손끝 자른 목장갑", ["fingerless_gloves"]), ("가위", ["scissors"]), ("=커튼", ["auditorium_curtain"]), ("붉은 벨벳 커튼", ["stage_curtain"]),
("객석 문", "장소(강당 문)"), ("닫힌 강당 문", "장소(강당 문)"), ("사회자 종이", ["emcee_paper"]), ("선영 안경", ["glasses_seonyoung"]),
("한강신보", ["newspaper_seoulmaeil"]), ("접힌 신문", ["newspaper_seoulmaeil"]), ("국그릇", ["bowls_spoons"]), ("숟가락·젓가락", ["bowls_spoons"]),
("숟가락·밥그릇", ["bowls_spoons"]), ("빈 밥그릇", ["bowls_spoons"]), ("국밥", ["gukbap"]), ("국밥값", ["scrap_money"]),
("납작한 판자", ["flat_board"]), ("펄럭이는 비닐", ["white_vinyl"]), ("찢어진 비닐", ["white_vinyl"]), ("머리 묶던 고무줄", ["hair_tie"]),
("깨진 화분", ["broken_flowerpot_shoe"]), ("사과 상자", ["apple_crate"]), ("아교 붓", ["glue_brush"]),
("=연필", ("kwak_pencil", "pencil")), ("공책과 연필", ["composition_notebook", "pencil"]), ("오선지·연필", ["staff_paper", "pencil"]),
("극장 반짝이 막", ["theater_stage_1970s", "manseok_clarinet"]), ("자갈", "지면(배경)"), ("=공책", ["composition_notebook"]),
("오선지", ["staff_paper"]), ("선반의 깡통들", ["workshop_cans"]), ("선반 위 깡통들", ["workshop_cans"]),
("구리 파이프·양은 냄비", ["copper_pipe_and_pot"]), ("깡통 한 자루", ["can_sack_3_9"]), ("고른 깡통", ["chosen_can"]),
("찾을 돈", ["mija_savings_can"]), ("굵은 펜", ["marker_pen"]), ("보고서", ["report_cover"]), ("선풍기", ["desk_fan"]),
("구두 끝", ["choi_shoes"]), ("양철 지붕", ["tin_roof_1950s"]), ("복도 화분", ["corridor_plant"]), ("흰 원피스", ["borrowed_white_dress"]),
("걸레", ["rag"]), ("곽 영감의 진짜 바이올린", ["kwak_violin"]), ("은주의 진짜 바이올린 케이스", ["eunju_real_violin_case"]), ("사다리", ["ladder_attic"]), ("전세 버스", ["charter_bus"]),
("앞 유리 손글씨", ["bus_sign_galdaeseom"]), ("꽃무늬 앞치마", ["sunrye_apron"]), ("높은 유리문", "장소(회관 문)"), ("복도 거울", ["hallway_mirror"]),
("빈 줄 봉투", ["empty_string_envelope"]), ("라디오 수리점", ["radio_repair_shop_radios"]), ("새 E현", ["taejun_spare_e_string"]),
("끊어진 E현", ["dongguri"]), ("나무못", ["dongguri"]), ("객석 의자 등받이", "장소(객석 의자)"), ("봉투(사회자)", ["result_envelope"]),
("마이크", ["microphone"]), ("=북채", ("drumstick_spoons", "dongmin_drumsticks_2003")), ("상장", ["award_certificate"]),
("꽃다발", ["bouquet"]), ("카메라", ["camera_flash"]), ("언덕 비탈 현수막", ["park_banner_slope"]), ("현수막 '공원 개장", ["concert_banner"]),
("이삿짐", ["moving_trucks"]), ("이주 명단", ["relocation_list"]), ("흙 덮는 장비", ["earth_dozer"]),
("클라리넷", ["manseok_clarinet"]), ("클라리넷 케이스와 바이올린 케이스", ["pawned_violin_case"]), ("계산대", ["pawnshop_showcase"]),
("작은 나무 무대", ["small_wooden_stage"]), ("접이식 의자", ["folding_chair"]), ("호루라기", ["whistle_rollbook"]), ("큰 냄비", ["deoksu_big_pot"]),
]
