from common import X

E03 = "2003 Seoul"
SPEC = {
"pawnshop_showcase": X(
  "나무 틀 유리 진열장과 계산대", "진열장 150×50cm·높이 95cm", ["#6E5236", "#DDE6E8", "#C9A24A", "#E8E2D6"],
  "유리에 손자국, 나무 틀 모서리 닳음", "윗면도 유리인 진열장 안에 손목시계·금반지·사진기가 누워 있음(상표 없음). 그 위에 케이스를 올림",
  "전당포의 계산대 — 만석과 선영이 스치는 자리(2-8), 동전이 쏟아지는 자리(3-33)",
  ("a wooden glass display counter in a small pawnshop", "a waist-high wooden counter with a glass top and glass front, wristwatches, gold rings and an old camera lying inside, no brand marks",
   "wood, glass", "150 by 50cm, 95cm high", "fingerprints on the glass, worn wooden corners"), notes="C→B(2-8·3-33 두 씬)"),
"iron_hook": X("긴 쇠갈고리(나무 손잡이)", "길이 90cm", ["#4A4A4A", "#8A6A45", "#8E4B2A"], "녹, 손잡이 손때", "곧은 쇠막대 끝이 갈고리로 굽음, 위에 나무 손잡이",
  "갈고리 아주머니의 도구(1-1 번쩍 치켜듦)", ("a long iron scavenging hook", "a straight iron rod curved into a hook at the end with a wooden handle", "iron, wood", "90cm long", "rusty, handle polished by hands"),
  ref="research/notes.md [A] 18쪽(줍는 사람들) — 갈고리 형태는 미확인"),
"soap_truck": X("소형 트럭(적재함, 문짝에 흰 페인트 가공 공장명 — 글자는 식자)", "길이 452cm(1톤 캡오버 트럭)", ["#3E6E5A", "#E8E2D6", "#5A5E62"], "엔진이 쿨럭, 칠 바램",
  "1980년대 소형 화물트럭, 문짝 흰 글씨 자리(빈 띠)", "은주의 첫 감별 '비누 공장 차요. 기침하잖아요.'(1-1)",
  ("a small 1980s cargo truck", "a cab-over small truck with an open cargo bed, a blank white painted band on the door for lettering", "steel", "452cm long", "faded paint")),
"ironworks_truck": X("덤프트럭(적재함을 기울임)", "길이 650cm", ["#2E4A6E", "#8E4B2A", "#5A5E62"], "적재함 안쪽 녹, 쇳가루",
  "적재함이 기울어 쇳더미를 쏟는 덤프트럭", "쇳소리가 와르르(1-1)", ("a 1980s dump truck tipping its bed", "a dump truck with its rear bed tilted up pouring scrap iron", "steel", "650cm long", "rusty bed")),
"yellow_painted_iron": X("노란 칠한 쇳덩이", "20×12×8cm", ["#E8C23A", "#3A3A3A", "#8E4B2A"], "긁으면 노란 칠이 벗겨져 거무튀튀한 쇠",
  "울퉁불퉁한 덩어리, 한쪽 칠이 긁힘", "미자의 '금빛!' → '철이에요'(1-2)", ("a lump of iron painted yellow", "an irregular metal lump with yellow paint, one side scraped to dark iron", "iron, paint", "20 by 12 by 8cm", "scratched paint")),
"bottle_caps": X("병뚜껑(왕관형) 한 주먹", "지름 3.2cm", ["#C7CBC9", "#C0392F", "#E8C23A"], "찌그러지고 녹 점", "톱니 테두리 금속 병뚜껑들(무늬 없음)",
  "동민의 보물 '반짝이잖아요'(1-3), '병뚜껑 백 개'(3-10)", ("a handful of crown bottle caps", "metal crown caps with crimped edges, plain colors, no logos", "tinplate", "3.2cm across", "bent and rusty")),
"polishing_cloth": X("부드러운 융 천", "30×30cm", ["#E8DCC0", "#C8B28A"], "빨아 보풀", "작은 정사각 천", "곽 영감이 금 따라 먼지를 닦음(1-3)",
  ("a soft polishing cloth", "a small square of soft flannel", "cotton flannel", "30 by 30cm", "pilled from washing")),
"kimchi_jjigae": X("김치찌개(양은 냄비)", "냄비 지름 20cm", ["#C0392F", "#D9C9A0", "#F2E6D8"], "보글보글", "양은 냄비에 붉은 국물·김치·두부",
  "말 없는 저녁(1-4)", ("a pot of kimchi stew", "a yellowish aluminum pot of bubbling red stew with kimchi and tofu", "aluminum pot", "20cm pot", "steaming")),
"tool_sack": X("공구 자루(천 자루, 망치·스패너)", "50×30cm", ["#8A7A5A", "#5A5E62"], "기름 얼룩", "입을 묶은 천 자루에 공구 손잡이가 삐져나옴",
  "만석이 들고 나가는 핑계(1-4)", ("a canvas tool bag", "a tied canvas sack with a hammer handle and a wrench sticking out", "canvas, steel", "50 by 30cm", "oil stains")),
"chalk": X("흰 분필(끝이 쪼개짐)", "길이 8cm, 지름 1cm", ["#F4F2EC", "#C8C4BA"], "끝이 세로로 쪼개짐", "원통 분필",
  "은주의 귀 '분필 끝이 깨졌어요'(1-6)", ("a stick of white chalk with a split tip", "a cylindrical chalk stick whose tip is split lengthwise", "chalk", "8cm long", "split tip, chalk dust")),
"chalkboard": X("녹색 칠판(철판에 도료)", "180×90cm", ["#2E5A44", "#E8E2D6", "#8A6A45"], "지운 자국 뿌옇게", "벽에 건 녹색 칠판과 분필 받침",
  "공부방 교실(1-6)", ("a green school chalkboard", "a wall-mounted green board in a wooden frame with a chalk ledge, faint erased marks, no readable writing", "painted steel board, wooden frame", "180 by 90cm", "smudged")),
"dictation_notebook": X("받아쓰기 공책(국민학교)", "18×25cm", ["#E8DCC0", "#2B2B2B", "#C0392F"], "연필 글씨(식자 단계)", "칸 공책",
  "은주가 동민 공책을 봐 줌(1-6)", ("a child's dictation notebook", "an open notebook with square writing grids and pencil marks that are not readable", "paper", "18 by 25cm", "smudged pencil")),
"xray_film_line": X("빨랫줄에 넌 X선 필름(병원 고물)과 비눗물 대야", "필름 35×43cm, 대야 지름 45cm", ["#3E4A55", "#E8EEF2", "#A7ACB0"], "깨끗이 씻음, 의료 글자 없음",
  "빨래집게로 넌 필름 4장, 아래 양은 대야", "뼈다귀 북 재료(1-12) — bone_drum__s1_film_drying과 같은 그림",
  ("X-ray films drying on a line over a basin", "four translucent blue-gray film sheets with faint white bones, pinned with wooden clothespins on a line, a dented basin of soapy water below, no letters",
   "film, metal basin", "films 35 by 43cm", "washed clean")),
"workbench_screws": X("작업대 위 나사못", "길이 2~5cm", ["#A7ACB0", "#8E4B2A"], "녹 점", "흩어진 나사못 몇십 개", "뚱보 소리에 달달 떪(1-12)",
  ("a scatter of loose screws", "dozens of small wood screws on a workbench", "steel", "2 to 5cm", "rust dots")),
"calendar_junkshop": X("벽걸이 숫자 달력(한 장씩 넘김)", "38×53cm", ["#F2EEE4", "#2B2B2B", "#C0392F"], "누렇게 바램", "위에 한복 입은 여인 사진(누구도 닮지 않은 얼굴), 아래 날짜 칸(글자 대신 칸만)",
  "4월→5월 넘어감(1-13)", ("a monthly wall calendar", "a wall calendar with a photo of a woman in hanbok on top (generic face, not a real person) and a blank grid of day boxes, no readable numbers", "paper", "38 by 53cm", "yellowed")),
"calendar_tent": X("천막 기둥에 건 달력", "26×38cm", ["#F2EEE4", "#2B2B2B", "#C0392F"], "바람에 들썩", "작은 숫자 달력(글자 없이)",
  "계속 9월(2-1 개그)", ("a small wall calendar hanging on a tent pole", "a small monthly calendar with a blank day grid, no readable numbers", "paper", "26 by 38cm", "curling pages")),
"broken_piano": X("부서진 업라이트 피아노", "높이 125cm, 폭 145cm", ["#2A1E18", "#F2EEE4", "#C7CBC9"], "칠이 깨지고 건반 빠짐", "앞판을 뜯어 쇠줄과 해머가 드러난 업라이트 피아노",
  "곽 영감 '이거 한 대면 일 년은 간다'(2-1)", ("a broken upright piano", "an old upright piano with the front panel removed, steel strings and hammers exposed, some keys missing", "wood, steel", "125cm high, 145cm wide", "cracked dark finish")),
"dish_towel": X("행주(면)", "35×35cm", ["#F2EEE4", "#C8C2B4"], "국물 얼룩", "접은 흰 면 행주", "지휘봉을 탁탁 텀(2-1)",
  ("a cotton dish towel", "a folded white cotton cloth", "cotton", "35 by 35cm", "broth stains")),
"city_bus": X("1980년대 시내버스 내부(토큰함)", "버스 길이 1050cm", ["#C7CBC9", "#3E6E8E", "#C9A24A"], "닳은 좌석", "운전석 옆 요금통(앞문 승차, 안내양 없음), 손잡이 줄, 좁은 좌석. 외부 도색 보라·하늘색(미확인)",
  "섬 아이들이 자루를 안고 탐(2-3)", ("the interior of a 1980s city bus", "rows of worn seats, hanging straps, a fare box beside the driver's seat at the front door, no bus conductor", "steel, vinyl seats", "bus 1050cm long", "worn seats")),
"taejun_rag": X("송진 닦는 헝겊(융)", "20×20cm", ["#F2EEE4", "#C8C2B4"], "송진 가루", "작은 천", "태준의 냉정(2-4 스윽 스윽)",
  ("a small soft cloth for wiping rosin", "a small square of soft flannel with white rosin dust", "flannel", "20 by 20cm", "dusty with rosin")),
"survey_form": X("'갈대섬 가구 조사표'(식자) 등사 서류", "19×26cm", ["#E8E2D0", "#2B2B2B"], "봉투에서 삐져나옴", "칸이 그려진 양식지(글자는 식자)",
  "섬이 서류가 됨(2-5)", ("a mimeographed survey form", "a ruled form sheet written horizontally with blank boxes and illegible text marks", "paper", "19 by 26cm", "slightly creased")),
"choi_memo": X("작은 수첩(검은 비닐 표지)", "9×15cm", ["#1E1E1E", "#F2EEE4"], "볼펜 글씨(식자)", "세로로 여는 수첩",
  "'특이 사항 없음'(2-7)", ("a small pocket notebook", "a black vinyl-covered pocket notebook opened to a page with a short line of illegible pen marks", "vinyl, paper", "9 by 15cm", "bent corners")),
"pawnshop_sign": X("'만복전당포' 간판(식자, '복' 자 반쯤 떨어져 매달림)", "300×60cm", ["#F2EEE4", "#2B2B2B", "#8E4B2A"], "칠 벗겨짐, 한 글자 판이 비뚤게 매달림",
  "긴 가로 간판판, 글자판 하나가 한쪽 못에만 매달려 기욺(글자 없이 판만)", "시장 골목 끝 전당포(2-8)",
  ("an old shop sign board", "a long horizontal sign board with blank letter plates, one plate hanging crooked from a single nail", "painted metal", "300 by 60cm", "peeling paint, rust")),
"pawn_ticket_seonyoung": X("선영의 전당표(비교적 새것)", "12×18cm", ["#E8DCB4", "#B0302A", "#2B2B2B"], "덜 바램, 방금 찍은 빨간 도장",
  "만석 것과 같은 양식, 새 도장", "선영의 바이올린(2-8 쾅)", ("a newer pawn ticket", "a small printed form slip with a blank title bar, ruled rows of illegible marks and a fresh red square stamp", "thin paper", "12 by 18cm", "only slightly yellowed")),
"pawn_stamp": X("전당포 고무 도장·인주", "도장 3×3cm", ["#B0302A", "#5A3A24"], "", "손잡이 달린 네모 도장과 빨간 인주 통", "쾅!(2-8)",
  ("a rubber stamp and red ink pad", "a square rubber stamp with a wooden handle beside a round red ink pad", "wood, rubber", "3 by 3cm stamp", "ink-stained")),
"electronics_shop_radio": X("전파사 진열대 라디오", "가로 30cm", ["#8A6A45", "#E3D8BE", "#C7CBC9"], "진열품", "나무 장식 탁상 라디오, 스피커 천",
  "관악기 소리에 만석이 걸음을 재촉(2-9)", ("a tabletop radio in an electronics repair shop window", "a wood-cased tabletop radio with a cloth speaker grille and a dial, no brand marks", "wood, cloth", "30cm wide", "dusty")),
"trash_mound_wet": X("천막 뒤 젖은 쓰레기 더미", "높이 150cm", ["#5A5048", "#F2F0EA", "#9A9690"], "비에 젖음", "젖은 비닐·깡통·나뭇조각이 엉킨 더미",
  "동그리가 던져지는 곳(2-10), 밤새 찾는 곳(2-12)", ("a wet heap of trash behind a tent", "a mound of tangled wet plastic sheets, tin cans and broken wood", "mixed trash", "150cm high", "soaked with rain")),
"mija_stick": X("나무 막대기", "길이 100cm", ["#8A6A45", "#5A4A3A"], "젖음", "곧은 막대", "비닐을 들춤(2-12)",
  ("a plain wooden stick", "a straight wooden stick", "wood", "100cm long", "wet")),
"notice_1988_jan": X("정식 통보 공문(빨간 도장 둘, 가로쓰기)", "19×26cm", ["#E8E2D0", "#2B2B2B", "#C0302A"], "바람에 귀퉁이 들썩", "1987년 알림과 같은 양식, 도장이 둘",
  "1988년 1월 '8월 말까지'(2-15)", ("an official eviction notice with two red seals", "a portrait notice sheet written horizontally with a blank title line, illegible typed lines and two red square seals", "paper", "19 by 26cm", "corner flapping")),
"coal_stove_kettle": X("연탄난로와 양은 주전자", "난로 높이 60cm, 주전자 지름 20cm", ["#3A3A3A", "#D9C9A0", "#C0392F"], "그을음, 김",
  "원통형 연탄난로(22공탄 2장 들어감) 위 노란 양은 주전자, 위로 올라가는 양철 연통", "주민 회의의 김(2-15)", ("a coal-briquette heater with an aluminum kettle", "a cylindrical briquette stove with a tin stovepipe rising from it and a yellowish aluminum kettle steaming on top", "cast iron, aluminum", "stove 60cm high", "sooty")),
"kicked_can": X("빈 깡통", "지름 7cm·높이 11cm", ["#B9BDBF", "#8E4B2A"], "찌그러짐", "통조림 깡통", "미자의 분노 '깡!'(2-16)",
  ("an empty dented tin can", "a small unlabeled food can, dented", "tinplate", "7cm across", "dented and rusty")),
"coal_brazier": X("공방 연탄 화덕", "지름 35cm, 높이 40cm", ["#3A3A3A", "#C7843A", "#8A8A8A"], "그을음", "원통 화덕 속 22공탄(지름 15.8cm·높이 15.2cm)", "겨울 공방(2-17)",
  ("a coal-briquette brazier", "a round brazier holding a cylindrical coal briquette with 22 holes (15.8cm across, 15.2cm tall) glowing faintly", "iron, clay", "35cm across", "sooty")),
"scissors": X("가위(쇠)", "길이 20cm", ["#8E9396", "#2A2A2A"], "", "검은 손잡이 쇠가위", "목장갑 손가락 끝을 잘라 줌(2-17)",
  ("a pair of steel scissors", "plain steel scissors with black handles", "steel", "20cm long", "slightly worn")),
"fingerless_gloves": X("손끝을 자른 목장갑", "아이용 21cm, 손가락 끝 1.5cm 잘림", ["#ECE8DC", "#B9AE96"], "잘린 끝 올 풀림", "목장갑 다섯 손가락 끝을 가위로 잘라 손끝이 나옴",
  "곽 영감의 배려 — 겨울 연습(2-17)", ("cotton work gloves with the fingertips cut off", "white knitted gloves with all five fingertips snipped off", "knitted cotton", "21cm long", "frayed cut ends"),
  notes="outfit_schedule는 2-14~2-17에 이 장갑을 넣었으나 대본상 자르는 것은 2-17 — 애매(보고)"),
"auditorium_curtain": X("학교 강당 무대 커튼", "높이 500cm", ["#7A2A30", "#5A1E22"], "바램", "자주색 무대 커튼", "예선 무대 옆(2-18)",
  ("a faded school stage curtain", "a plain maroon stage curtain with folds", "velvet-like cloth", "500cm high", "faded")),
"emcee_paper": X("사회자 순서지", "A4 21×29.7cm", ["#F2EEE4", "#2B2B2B"], "", "한 장 종이(글자 식자)", "본선 진출 발표(2-19)",
  ("a sheet of announcement paper", "a single sheet with illegible typed lines", "paper", "21 by 29.7cm", "folded once")),
"broken_flowerpot_shoe": X("깨진 화분·고무신 한 짝", "화분 지름 15cm, 고무신 길이 24cm", ["#B5653A", "#2A2A2A", "#9A9690"], "버려짐",
  "손전등 원 안의 깨진 토분과 검정 고무신 한 짝", "밤의 쓰레기 산(2-27)", ("a broken clay flowerpot and a single black rubber shoe", "a cracked terracotta pot and one old black Korean rubber shoe lying on trash", "clay, rubber", "pot 15cm, shoe 24cm", "discarded"),
  notes="고무신은 1987년 서울 일상화가 아님(고증) — 버려진 물건이라 무방"),
"glue_brush": X("아교 붓과 아교 중탕 그릇", "붓 길이 18cm", ["#8A6A45", "#D9A441", "#C7CBC9"], "아교가 굳은 붓털", "작은 붓, 중탕 그릇(철제 아님)",
  "사흘 밤의 수리(3-1 회상)", ("a hide-glue brush and glue pot", "a small brush with hardened bristles and a small glue pot in a water bath (not iron)", "wood, bristle, ceramic", "brush 18cm", "amber glue crust")),
"doenjang_jjigae": X("된장찌개(양은 냄비)", "냄비 지름 20cm", ["#9A7A40", "#D9C9A0", "#7FB77E"], "보글보글", "양은 냄비에 된장 국물·두부·호박",
  "동그리가 집에 들어온 저녁(3-2)", ("a pot of soybean paste stew", "a yellowish aluminum pot of brown stew with tofu and zucchini", "aluminum pot", "20cm pot", "steaming")),
"theater_stage_1970s": X("1970년대 극장 쇼 무대 반짝이 막·악단 보면대", "막 높이 5m, 보면대 높이 110cm", ["#C9A24A", "#B03A6A", "#2A2A2A"], "회상(세피아)",
  "반짝이 술 막, 무대 아래 악단석의 쇠 보면대", "만석의 과거(3-3)", ("a 1970s theater show stage tinsel curtain and band music stands", "a glittering tinsel curtain above a small band pit with plain steel music stands", "tinsel, steel", "curtain 500cm high", "shown in sepia memory", "1970s Seoul"),
  era="1970년대 서울(회상)"),
"copper_pipe_and_pot": X("구리 파이프와 양은 냄비", "파이프 30cm, 냄비 지름 18cm", ["#B5653A", "#D9C9A0", "#8E4B2A"], "찌그러짐", "곧은 구리관, 손잡이 달린 양은 냄비",
  "구리는 둥글고 양은은 날카로워요(3-6)", ("a copper pipe and an aluminum pot", "a straight copper tube and a dented yellowish aluminum saucepan with a handle", "copper, aluminum", "pipe 30cm, pot 18cm", "dented")),
"can_sack_3_9": X("깡통 한 자루(쏟음)", "자루 60×90cm", ["#B9BDBF", "#E4E0D4", "#8E4B2A"], "", "바닥에 와르르 퍼지는 여러 크기 깡통", "새 단원의 악기 재료(3-9)",
  ("a sack of tin cans spilled on a floor", "dozens of unlabeled tin cans of many sizes scattered from an open woven sack", "tinplate", "sack 60 by 90cm", "assorted rust")),
"chosen_can": X("은주가 고른 맑은 깡통(→2호 몸통)", "지름 13cm·높이 15cm", ["#C4C8CA", "#A0522D"], "점 녹", "작은 분유 깡통", "'이거요.'(3-9)",
  ("a clean unlabeled milk-powder tin", "a small cylindrical tin can", "tinplate", "13cm across, 15cm tall", "a few rust dots")),
"marker_pen": X("굵은 유성 매직펜", "길이 13cm", ["#1E1E1E", "#F2F0EA"], "", "굵은 원통 펜", "'찾을 돈'(3-11)",
  ("a thick permanent marker", "a fat cylindrical marker pen with a black cap", "plastic", "13cm long", "used")),
"report_cover": X("보고서 표지·본문(식자, 가로쓰기)", "19×26cm", ["#F2EEE4", "#2B2B2B", "#C0302A"], "땀방울에 한 글자 번짐", "표지 한 장 + 본문, 결재 도장 자리",
  "최 계장의 이주 대책(3-12)", ("a typed government report cover", "a report cover with a blank title block and lines of illegible typed text, one smudged spot from a drop of sweat", "paper", "19 by 26cm", "one blurred spot")),
"desk_fan": X("사무실 선풍기(철망, 좌우 회전)", "높이 50cm, 날개 지름 30cm", ["#5E8A9A", "#C7CBC9", "#2A2A2A"], "", "철망 덮개 선풍기, 고개를 돌림", "덜덜덜(3-12)",
  ("a 1980s office electric fan", "an oscillating desk fan with a wire guard", "steel, plastic", "50cm high", "slightly rattling")),
"office_stamp": X("결재 도장(나무)·빨간 인주", "도장 지름 2cm", ["#B0302A", "#8A6A45"], "", "둥근 나무 도장", "과장의 승인 '탁'(3-12)",
  ("a wooden seal stamp and red ink pad", "a round wooden name seal beside a red ink pad", "wood", "2cm seal", "ink-stained")),
"tin_roof_1950s": X("회상: 1950년대 판잣집 양철 지붕(편 깡통 생철)", "지붕 폭 300cm", ["#8E4B2A", "#9DA3A6", "#5A4A3A"], "녹슴, 빗소리",
  "펴서 이은 깡통 철판·천막천 조각 지붕", "어린 최 계장의 기억(3-12)", ("a 1950s shanty roof of flattened tin cans", "a patchwork roof of flattened rusty tin-can sheets and canvas scraps over plywood walls", "tinplate, canvas", "300cm wide", "rusty, rain drumming", "1950s Seoul"),
  era="1950년대 서울(회상)", ref="https://theme.archives.go.kr/next/koreaOfRecord/panjaChon.do (국가기록원 판자촌)"),
"corridor_plant": X("구청 복도 화분", "화분 지름 30cm, 높이 90cm", ["#5A8A5A", "#B5653A"], "", "토분에 심은 관엽식물", "손수건을 짜 똑똑(3-13)",
  ("a potted plant in an office corridor", "a leafy green plant in a terracotta pot", "clay pot", "90cm tall", "ordinary")),
"relocation_notice": X("이주 공문(1988년 7월, 가로쓰기)", "19×26cm", ["#F2EEE4", "#2B2B2B", "#C0302A"], "압정으로 천막 기둥에", "공문 양식, 빨간 도장",
  "이주는 공연 뒤, 같은 동네(3-14)", ("an official relocation notice", "a portrait notice sheet written horizontally with illegible typed lines and a red square seal", "paper", "19 by 26cm", "pinned to a pole")),
"kwak_wood_piece": X("곽 영감이 사포질하는 나뭇조각", "30×5×3cm", ["#D6B07A", "#B48A55"], "", "길쭉한 나뭇조각(무엇을 만드는지 안 보임)", "몰래 무언가를 궁리하는 손(1-9)",
  ("a long piece of pale wood being sanded", "a plain elongated piece of wood", "pine", "30 by 5 by 3cm", "freshly sanded")),
"ladder_attic": X("고물상 사다리와 다락", "사다리 길이 250cm", ["#8A6A45", "#5A4A3A"], "삐걱, 먼지", "나무 사다리가 천장 다락 구멍으로", "다락의 바이올린(1-9 시선, 3-15)",
  ("a wooden ladder up to a small attic hatch", "a simple wooden ladder leaning into a square opening in the ceiling", "wood", "250cm long", "dusty")),
"rag": X("걸레(면)", "30×30cm", ["#C8C2B4", "#8A8070"], "", "접은 걸레", "본선 전날 동그리를 닦음(3-15)",
  ("a cleaning rag", "a folded worn cotton rag", "cotton", "30 by 30cm", "worn")),
"hallway_mirror": X("무대 뒤 복도 거울", "60×90cm", ["#DDE6E8", "#6E5236"], "", "나무 테 거울", "흰 원피스의 은주(3-17)",
  ("a wall mirror in a backstage corridor", "a rectangular mirror in a plain wooden frame", "glass, wood", "60 by 90cm", "ordinary")),
"empty_string_envelope": X("빈 줄 봉투(공장 시절)", "10×10cm", ["#D9C79A", "#8A6A40"], "빛바램, 비어 있음", "작은 종이 봉투(글자 없음)",
  "공장 시절 줄은 동그리에 걸린 것이 마지막(3-18)", ("an empty faded string envelope", "a small square paper envelope, empty and flattened, no readable letters", "paper", "10 by 10cm", "faded")),
"radio_repair_shop_radios": X("회상: 라디오 수리점 선반의 라디오들", "선반 폭 200cm", ["#8A6A45", "#E3D8BE", "#C7CBC9"], "세피아", "선반 가득 진공관·트랜지스터 라디오",
  "은주가 본 적 없는 엄마의 장면(3-21)", ("shelves of old radios in a 1970s repair shop", "shelves crowded with tube and transistor radios, no brand marks", "wood, metal", "shelf 200cm wide", "shown in sepia", "1970s Seoul"),
  era="1970년대 서울(회상)"),
"dawn_truck": X("새벽 첫 트럭(불빛)", "길이 650cm", ["#5E7F99", "#F5D27A", "#2A2A2A"], "", "어둠 속 둑길을 넘는 트럭 전조등 두 개", "'새벽'(3-20 겹침)",
  ("a truck's headlights at dawn", "a dark truck silhouette with two headlights on an embankment road", "steel", "650cm long", "in blue-gray dawn light")),
"result_envelope": X("결과 봉투", "11×22cm", ["#F2EEE4", "#C9A24A"], "", "흰 봉투", "봉투 찢는 소리(3-27)",
  ("a white result envelope", "a plain white envelope being torn open", "paper", "11 by 22cm", "new")),
"microphone": X("유선 마이크(스탠드)", "마이크 길이 18cm", ["#2A2A2A", "#C7CBC9"], "", "검은 유선 핸드 마이크, 은색 망 머리", "대상 발표(3-27)",
  ("a corded handheld microphone", "a black handheld microphone with a silver mesh head and a cord", "metal", "18cm long", "ordinary")),
"bouquet": X("꽃다발(셀로판 포장)", "길이 45cm", ["#E8564A", "#F2C94C", "#7FB77E"], "", "셀로판으로 싼 꽃다발", "로비(3-28)",
  ("a bouquet of flowers in cellophane", "mixed flowers wrapped in clear cellophane with a ribbon", "flowers, cellophane", "45cm long", "fresh")),
"camera_flash": X("필름 카메라(플래시)", "가로 13cm", ["#2A2A2A", "#C7CBC9"], "", "자동 필름 카메라, 플래시 번쩍", "찰칵(3-28)",
  ("a 1980s compact film camera with flash", "a small black compact camera with a built-in flash, no brand marks", "plastic, metal", "13cm wide", "ordinary", "1988 Seoul")),
"bus_sign_galdaeseom": X("버스 앞 유리 손글씨 종이 '갈대섬'(식자)", "30×20cm", ["#F2EEE4", "#2B2B2B"], "", "앞 유리 안쪽에 테이프로 붙인 종이", "섬사람들의 버스(3-16)",
  ("a handwritten paper sign taped inside a bus windshield", "a sheet of paper with a thick blank marker frame, no readable letters", "paper, tape", "30 by 20cm", "slightly curled", "1988 Seoul")),
"moving_trucks": X("이삿짐 실은 트럭들", "길이 452cm(1톤 캡오버 트럭)", ["#3E6E5A", "#8A6A45", "#E8E2D6"], "", "짐칸에 장롱·이불 보따리를 실은 소형 트럭 줄", "섬을 떠남(3-32)",
  ("a line of small trucks loaded with household goods", "small cargo trucks with wardrobes, bundles and furniture roped in their beds", "steel", "452cm long each", "packed full", "1988 Seoul")),
"relocation_list": X("이주 명단(결재판)", "B4 25.7×36.4cm", ["#F2EEE4", "#2B2B2B"], "", "결재판에 끼운 명단, 볼펜 표시", "보고서대로(3-32)",
  ("a relocation list on a clipboard", "a ruled list on a clipboard with pen check marks and illegible lines", "paper, board", "25.7 by 36.4cm", "ordinary", "1988 Seoul")),
"earth_dozer": X("흙 덮는 불도저(추정)", "길이 500cm", ["#E8B83A", "#2A2A2A", "#8A6A45"], "흙투성이", "산 위 흙을 미는 불도저", "매립 종료(3-32)",
  ("a bulldozer spreading soil", "a bulldozer pushing fresh soil over a flat hilltop", "steel", "500cm long", "covered in dirt", "1990s Seoul"), ref="research/notes.md [A] 17쪽(불도저로 흙을 덮음)"),
"pawned_violin_case": X("전당포 창고의 바이올린 케이스(선영의 바이올린이 든 것)", "길이 78cm", ["#3A3A3A", "#9A9690"], "먼지가 두껍게",
  "오래된 케이스(선영의 빈 케이스와 다른 것)", "되찾는 순간(3-33)", ("a dusty old violin case from a pawnshop storeroom", "a closed old violin case under a thick layer of dust", "leatherette, wood", "78cm long", "thick gray dust", "1988 Seoul"),
  notes="선영의 빈 케이스는 선영이 들고 다니므로 맡긴 바이올린은 다른 케이스에 들어 있다고 봄(애매)"),
"park_banner_slope": X("언덕 비탈 현수막(천, 글씨 식자)", "500×90cm", ["#F2EEE4", "#2E5A8E", "#7FB77E"], "", "두 말뚝 사이 가로 현수막", "2003 공원 개장(3-31)",
  ("a horizontal cloth banner on a grassy slope", "a long cloth banner tied between two poles, blank lettering area", "cloth", "500 by 90cm", "new", E03), era="2003 서울"),
"concert_banner": X("작은 무대 현수막(천, 글씨 식자)", "400×80cm", ["#F2EEE4", "#2E5A8E", "#C9A24A"], "", "무대 옆 가로 현수막", "'바이올린 하은주 · 클라리넷 하만석'(3-34)",
  ("a stage-side cloth banner", "a long cloth banner with a blank lettering area", "cloth", "400 by 80cm", "new", E03), era="2003 서울"),
"small_wooden_stage": X("언덕 꼭대기 작은 나무 무대", "500×400cm, 높이 60cm", ["#B48A55", "#7FB77E"], "", "낮은 나무 판 무대, 앞에 접이식 의자 객석", "에필로그 음악회(3-34)",
  ("a small outdoor wooden stage on a grassy hilltop", "a low platform of wooden planks with folding chairs in front", "wood", "500 by 400cm, 60cm high", "new", E03), era="2003 서울"),
"eunju_real_violin_case": X("어른 은주의 바이올린 케이스(공연장 꼬리표들)", "길이 80cm", ["#2A2A30", "#E8DCC0", "#C9A24A"], "닳음, 꼬리표 주렁주렁(글씨 식자)",
  "검은 직사각 케이스 손잡이에 종이 꼬리표 여러 개", "은주가 바이올리니스트가 됨(3-34)", ("a well-traveled violin case with many tags", "a black oblong violin case with many paper luggage tags tied to the handle, tags blank", "nylon, wood", "80cm long", "scuffed from travel", E03), era="2003 서울"),
"whistle_rollbook": X("호루라기·출석부(2003)", "호루라기 5cm, 출석부 22×30cm", ["#C7CBC9", "#2E4A7A", "#F2EEE4"], "", "목에 건 금속 호루라기, 겨드랑이의 출석부", "체육 교사 미자(3-34)",
  ("a metal whistle on a cord and a class roll book", "a silver whistle on a lanyard and a blue hardcover roll book", "metal, paper", "whistle 5cm, book 22 by 30cm", "used", E03), era="2003 서울"),
"deoksu_big_pot": X("큰 냄비(국밥 육수)", "지름 32cm", ["#C7CBC9", "#E8E2D6"], "김이 샘", "뚜껑 덮은 큰 스테인리스 냄비", "국밥집을 이어받은 덕수(3-34)",
  ("a large lidded stockpot", "a big stainless steel pot with a lid, steam leaking", "stainless steel", "32cm across", "steaming", E03), era="2003 서울"),
"dongmin_drumsticks_2003": X("드럼 스틱(2003)", "길이 40cm", ["#D6B07A", "#9A7448"], "끝이 닳음", "나무 드럼 스틱 한 쌍", "타악기 연주자 동민(3-34)",
  ("a pair of wooden drumsticks", "two straight hickory drumsticks", "wood", "40cm long", "tips worn", E03), era="2003 서울"),
}
