from common import X

SPEC = {
"kwak_old_bow": X(
  "바이올린 활: 갈색 나무 활대, 흑단 손잡이(프로그), 말총 활털",
  "길이 74cm, 활대 굵기 0.8cm, 프로그 길이 5cm", ["#7A4A2A", "#2A2422", "#E8DFC8", "#B8B2A6"],
  "공장 시절에 쓰던 낡은 활. 활대 손잡이 쪽 감은 실이 닳아 반들, 활털이 누렇고 군데군데 빠져 듬성함, 프로그 모서리 칠 벗겨짐",
  "곧은 활대 끝이 도끼날 모양 머리, 손잡이 쪽에 검은 프로그와 나사 단추. 활털은 머리에서 프로그까지 팽팽",
  "동그리의 활. 1-11 은주가 쇠막대 쥐듯 움켜쥐자 곽 영감이 손가락을 펴 줌(검지 위·엄지 아래). 선영의 떨리는 손끝(1-11)",
  ("an old worn violin bow", "a straight brown wooden stick with a hatchet-shaped tip, a black frog with a small screw button at the grip end, horsehair stretched from tip to frog",
   "pernambuco-type brown wood, ebony frog, horsehair", "74cm long", "the grip wrapping worn shiny, the hair yellowed and thinned with a few strands missing, chipped finish on the frog")),
"drumstick_spoons": X(
  "나무 숟가락 2개(밥숟가락 크기)",
  "각 길이 20cm, 머리 4×3cm", ["#C9A06A", "#9A7448", "#6E5236"],
  "끝(숟가락 머리 뒷면)이 북을 쳐서 반질하게 닳음, 자루에 동민 손때",
  "보통 나무 숟가락 두 개. 숟가락 머리 둥근 뒷면으로 필름을 침",
  "뼈다귀 북의 북채(1-12 '동민, 나무 숟가락 두 개로 친다'). 동민이 등 뒤로 감춤(2-10), 대상 발표 때 무릎을 두드림(3-27)",
  ("a pair of wooden spoons used as drumsticks", "two plain wooden eating spoons with oval bowls, held by the handles, the round backs of the bowls used to strike",
   "pale wood", "each 20cm long", "the backs of the bowls worn smooth and shiny, handles darkened by a child's grip")),
"scrap_sack": X(
  "흰 PP 마대 포대(짠 비닐 자루)",
  "자루 폭 60cm·길이 90cm(빈 것), 채우면 지름 45cm 안팎", ["#E4E0D4", "#B8B2A2", "#7A6A50"],
  "흙물이 들어 누렇고 아랫부분이 거무죽죽, 올이 풀린 구멍 1~2곳, 입구를 끈으로 묶음",
  "직사각 자루. 짜인 줄무늬 결이 보임. 빈 자루는 납작하게 접혀 들림, 찬 자루는 울퉁불퉁 각진 고물 모양이 비침",
  "섬사람들의 생계. 은주가 학교 가기 전 채워야 하는 한 자루(1-2). 악기를 싸서 버스에 탐(2-3), 동민이 그 위에서 잠(3-15)",
  ("a woven plastic scrap sack", "a rectangular sack of woven white plastic strips, the weave texture visible, shown empty and folded and full and lumpy with scrap metal, mouth tied with string",
   "woven polypropylene", "60 by 90cm", "stained yellow-brown with mud, darker at the bottom, one or two frayed holes"),
  notes="PP 마대는 1970년대부터 국내 생산(고증 일부 확인)"),
"cotton_work_gloves": X(
  "흰 면 목장갑(편직)",
  "아이용 길이 21cm, 어른용 24cm", ["#ECE8DC", "#B9AE96", "#6E5A40"],
  "손가락 끝과 손바닥이 흙물로 회갈색, 손목 시보리는 비교적 흼, 검지 끝 올 풀림",
  "다섯 손가락 면장갑, 손목은 신축성 있는 시보리 단. 손바닥 코팅 없음",
  "쓰레기 산의 안전 차림(12세 기준: 아이들은 반드시 목장갑). 1-11 은주가 벗어 점퍼 주머니에 넣고 동그리를 받음. 2-17 곽 영감이 손가락 끝을 잘라 줌(fingerless_gloves)",
  ("a pair of white knitted cotton work gloves", "five-finger knitted cotton gloves with ribbed cuffs, no palm coating", "knitted cotton", "21cm long (child size)",
   "fingertips and palms stained gray-brown with dirt, cuffs still fairly white, a frayed fingertip")),
"rubber_boots": X(
  "검정 고무 장화(작업용)",
  "아이용 높이 30cm, 어른용 높이 38cm", ["#2A2A2C", "#4A4A4E", "#8A7258"],
  "진흙이 말라붙어 발목 아래가 회갈색, 고무가 접히는 발등에 잔주름, 밑창 홈에 진흙",
  "통이 넓은 무릎 아래 장화, 위 테두리 단순, 발목에 접힘 주름, 두꺼운 홈 밑창",
  "섬의 신발. 철벅 소리. 1-1 은주가 발가락을 꼼지락. 2-12~13 곽 영감 장화의 진흙(밤새 찾은 증거). 2-26 만석이 신고 산에 오름",
  ("a pair of plain black rubber work boots", "simple knee-high black rubber boots with a wide shaft, folding creases at the ankle, thick lugged soles",
   "black rubber", "30cm tall (child size), 38cm (adult)", "dried mud caked below the ankle, mud in the sole grooves")),
"big_black_boots": X(
  "검정 고무장화(어른 큰 치수, 순례 할머니가 내줌)",
  "높이 38cm, 발 길이 28cm(선영 발 23cm에 크다)", ["#1E1E20", "#3E3E42", "#8A7258"],
  "커서 발목이 헐렁하게 뜸, 진흙 튐",
  "어른 남자용 큰 검정 장화. 선영이 신으면 통이 넓게 남고 걸을 때 철벅",
  "섬이 선영을 받아들이는 첫 물건(1-7 '이거 신어'). 이후 선영의 고정 신발(1-7~2-2)",
  ("a pair of oversized black rubber boots", "large men's knee-high black rubber boots, very wide shaft, shown standing next to a small pair of women's shoes for scale",
   "black rubber", "38cm tall", "mud splashes, clearly too big for a young woman")),
"seonyoung_shoes": X(
  "여성 단화(인조가죽, 낮은 굽)",
  "길이 23cm, 굽 높이 2.5cm", ["#6A4A3A", "#3A2A22", "#8A7258"],
  "1-7 한 짝이 진흙에 박혀 진흙 범벅",
  "앞이 둥근 낮은 굽 단화, 발등에 가는 끈 하나",
  "섬에 맞지 않는 도시 신발. 진흙에 박혀 깡충깡충(1-7) → 검정 장화로 바뀜",
  ("a pair of low-heeled women's shoes", "round-toed low-heeled pumps with a thin strap across the instep", "brown leatherette", "23cm long, 2.5cm heel",
   "one shoe coated with wet mud up to the strap")),
"iron_rod": X(
  "둥근 쇠막대 토막",
  "길이 22cm, 지름 1.2cm", ["#5A5E62", "#8A9096", "#8E4B2A"],
  "검은 쇠에 녹 점, 쥐는 쪽은 손때로 반질, 두드리는 끝은 반짝",
  "곧은 원형 쇠막대. 양 끝이 무디게 잘림",
  "은주의 귀를 쓰는 도구. 쇳덩이를 두드려 철·구리를 가림(1-2), 깡통을 두드려 음을 셈(2-1)",
  ("a short iron rod", "a straight round iron bar with blunt cut ends", "iron", "22cm long, 1.2cm thick", "rust spots, the grip polished by a hand, the striking end bright")),
"red_rag_flag": X(
  "나무 막대 끝에 묶은 빨간 헝겊",
  "막대 길이 120cm, 헝겊 30×40cm", ["#C0392F", "#8E2A22", "#9A7448"],
  "헝겊 가장자리가 해지고 바람에 찢긴 술, 막대는 껍질 벗긴 나뭇가지",
  "구불한 나무 막대 꼭대기에 빨간 헝겊 한 장을 끈으로 묶음",
  "미자의 '내 구역' 표시(1-2). 본선 '한낮' 회상(3-20)",
  ("a red rag flag on a stick", "a crooked stripped wooden stick with a red cloth rag tied to the top with string", "wood, red cotton rag", "stick 120cm, rag 30 by 40cm",
   "frayed torn edges on the rag")),
"copper_pipe_piece": X(
  "구리 파이프 토막(진흙 묻음)",
  "길이 25cm, 지름 2cm, 한 번 구부러짐", ["#B5653A", "#7A4A2A", "#6E5A40"],
  "진흙 밑에서 붉은 갈색이 반짝, 끝은 찌그러져 납작",
  "중간이 둔각으로 구부러진 구리관 토막",
  "은주의 첫 감별 '소리가 둥글잖아요'(1-2). 곽 영감 저울에 오름(1-3)",
  ("a bent piece of copper pipe", "a short copper tube bent once at an obtuse angle, one end squashed flat", "copper", "25cm long, 2cm diameter",
   "half caked with mud, reddish-brown copper gleaming where wiped")),
"hanging_scale": X(
  "고물상 걸이 저울(용수철식 접시 저울, 둥근 눈금판·바늘)",
  "눈금판 지름 25cm, 접시 지름 40cm, 전체 높이 80cm", ["#D8D4C8", "#3A3A3A", "#7A7E80", "#C0392F"],
  "눈금판 유리가 누렇게, 쇠사슬과 접시에 녹",
  "들보에 걸린 둥근 눈금판(바늘 하나), 아래 갈고리에 쇠사슬 세 줄로 매단 넓은 쇠접시. 눈금은 선만(숫자 없음)",
  "섬의 돈. 고물값 '양은 두 근 반'(3-1). 바늘이 바르르 떨다 멈춤(3-20 겹침)",
  ("a hanging spring dial scale for scrap", "a round dial face with a single needle hanging from a beam, a wide iron pan hung below on three chains, dial marks as lines only",
   "steel, glass dial cover", "dial 25cm across, pan 40cm, 80cm tall overall", "yellowed dial glass, rust on the chains and pan"),
  notes="저울 종류(대저울·앉은뱅이·용수철)는 고증 확인, 고물상이 어느 것을 썼는지는 미확인 — 대본 '바늘'에 맞춰 용수철 눈금 저울"),
"workbench": X(
  "두꺼운 나무 작업대(소나무 상판), 앞쪽 서랍 2, 바이스",
  "길이 160cm, 폭 70cm, 높이 80cm, 상판 두께 6cm", ["#9A7448", "#6E5236", "#E3C79A", "#5A5E62"],
  "칼자국·아교 자국·톱밥, 모서리 닳음. 서랍 손잡이는 쇠고리",
  "두꺼운 상판에 네 다리, 앞쪽 오른편에 쇠 바이스, 상판 아래 서랍 둘, 밑에 톱밥 소복",
  "곽 영감의 손이 일하는 자리. 동그리를 내놓는 곳(2-13·3-1), 진짜 바이올린을 푸는 곳(3-15), 서랍의 빈 줄 봉투(3-18)",
  ("an old woodworking workbench", "a thick plank top on four legs, a steel bench vise at the front right, two drawers with iron ring pulls under the top, wood shavings piled underneath",
   "pine, steel vise", "160 by 70cm, 80cm tall", "knife cuts, glue stains and sawdust on the top, worn corners")),
"sawdust": X(
  "소나무·가문비 톱밥과 대팻밥",
  "작업대 밑 더미 지름 50cm·높이 10cm", ["#E3C79A", "#C9A06A", "#9A7448"],
  "새 톱밥은 밝고 아래는 눅눅하게 짙음",
  "작업대 밑에 소복한 톱밥 더미, 사이사이 말린 대팻밥",
  "녹슨 고물 사이 '작업대 밑에만 톱밥'(1-3) — 곽 영감이 아직 나무를 깎는다는 증거. 웃음에 떠오르는 톱밥(3-15)",
  ("a small pile of sawdust and wood shavings", "a soft mound of fine sawdust with curled shavings mixed in", "pine sawdust", "pile 50cm across, 10cm high", "fresh pale on top, darker and damp underneath")),
"wrap_cloth": X(
  "낡은 무명 천(바래진 줄무늬)",
  "70×50cm", ["#D8CDB4", "#8A7A60", "#5E7F99"],
  "빨아서 해진 무명, 가장자리 올 풀림, 연한 남색 줄 두 줄",
  "직사각 천. 동그리를 감싸 길쭉한 꾸러미로, 펴면 접힌 자국",
  "동그리가 세상에 나오는 포장(1-11 곽 영감이 갠 천을 은주 손에), 고친 동그리를 덮음(2-13·2-14)",
  ("a worn cotton wrapping cloth", "a rectangular cotton cloth with two faded thin blue stripes, shown folded and wrapped into a long bundle", "faded cotton", "70 by 50cm", "softened by washing, frayed edges")),
"scrap_money": X(
  "1987년 지폐·동전(도안 없음 — 크기·색만)",
  "천 원권 15.1×7.6cm, 동전 10원 지름 2.29cm(황동)·50원 2.16cm·100원 2.4cm(백동)", ["#9A86B0", "#C9A24A", "#C7CBC9"],
  "구겨진 지폐, 손때 묻은 동전",
  "직사각 지폐 한 장(도안 대신 단색 면과 가는 테두리), 둥근 동전 몇 개(무늬 없이 테두리만)",
  "고물값(1-3·3-1), 선영의 이자(2-8), 국밥값(2-21), 미자의 '찾을 돈'(3-11·3-33). 동전으로 라디오 나사를 풂(1-5)",
  ("plain placeholder paper money and coins", "one rectangular banknote shown only as a flat tinted paper with a thin border and no design, several round coins shown only with rims and no design",
   "purplish paper note, brass and silvery cupronickel coins", "note 15.1 by 7.6cm, coins 2.16 to 2.4cm", "crumpled note, worn coins"),
  notes="실제 화폐 도안 금지(style_guide). 크기·색은 한국은행 규격(고증 확인)"),
"kerosene_stove": X(
  "심지식 석유곤로(철판 몸통·칠)",
  "지름 30cm, 높이 32cm", ["#3E6E8E", "#2A2A2A", "#C7CBC9", "#E8944A"],
  "칠이 벗겨지고 그을음, 위 받침살에 검은 탄 자국",
  "바닥의 원통형 기름통(주입구 뚜껑), 위에 둥근 화구와 받침살 셋, 앞에 심지 올리는 작은 손잡이, 화구 창으로 파란 불꽃",
  "판잣집 저녁(1-4 냄비 달각, 3-2 된장찌개)",
  ("a 1980s Korean wick-type kerosene cooking stove", "a cylindrical fuel tank at the base with a filler cap, a round burner on top, three pot-support prongs, a small wick-adjust knob at the front, a window showing a blue flame",
   "painted sheet steel", "30cm diameter, 32cm tall", "chipped paint, soot stains on the top"),
  notes="구조는 고증 일부 확인, 크기·색은 미확인"),
"low_table": X(
  "접이식 둥근 밥상(호마이카 상판, 쇠다리)",
  "지름 60cm, 높이 30cm", ["#B5654A", "#E8D8B8", "#5A5E62"],
  "상판 가장자리 칠이 벗겨지고 뜨거운 냄비 자국 동그라미",
  "둥근 상판 아래 접히는 쇠다리 넷",
  "말 없는 집의 밥상. 젓가락이 멈춤(1-4), '밥이나 먹어'(2-24), 동그리가 밥상 옆에(3-2)",
  ("a low round folding dining table", "a round tabletop on four folding metal legs", "laminated board, steel legs", "60cm across, 30cm tall", "chipped edge, a pale ring mark from a hot pot")),
"bowls_spoons": X(
  "스테인리스 밥그릇·국그릇(뚜껑 있음), 스테인리스 숟가락·젓가락",
  "밥그릇 안지름 10.5cm·높이 6cm(1976 서울시 규격), 국그릇 지름 14cm, 숟가락 20cm, 젓가락 21cm", ["#C7CBC9", "#8E9396", "#E8E2D6"],
  "잔흠집, 밥그릇 테두리 찌그러짐 하나",
  "둥근 스테인리스 공기와 국그릇, 납작한 숟가락, 납작한 쇠젓가락",
  "동민이 밥그릇을 '통' 두드림(1-4), 은주의 숟가락 '딸그락'(2-20), 만석이 빈 밥그릇을 '팅' — 솔(3-3)",
  ("a set of stainless steel rice bowl, soup bowl, spoon and flat chopsticks", "round stainless rice bowl with lid, a wider soup bowl, a flat spoon and flat metal chopsticks", "stainless steel",
   "rice bowl 10.5cm across and 6cm tall, spoon 20cm", "fine scratches, one small dent in a rim")),
"neck_towel": X(
  "흰 면 수건(기념 타월)",
  "길이 80cm, 폭 32cm", ["#EFEDE6", "#C8C2B4", "#5E7F99"],
  "누렇게 바래고 쇳가루 얼룩, 한쪽 끝에 바랜 한 색 염색 인쇄 글자(식자 단계 — 그림엔 흐린 띠)",
  "길쭉한 수건을 목에 걸고 양 끝을 앞에서 늘어뜨림. 문고리에 걸면 축 처짐",
  "만석의 인사: 말없이 풀어 문고리에 검(1-4). 비에 젖어 끝에서 빗물(2-10)",
  ("a worn white cotton towel worn around the neck", "a long narrow towel draped around the neck with ends hanging down, a faded one-color dyed band near one end with no readable letters",
   "cotton terry", "80 by 32cm", "yellowed, smudged with iron dust"),
  notes="기념 수건 글씨는 단순 염색 인쇄(고증)"),
"handcart": X(
  "리어카(철 파이프 틀, 나무 바닥, 고무바퀴 2)",
  "전체 길이 약 200cm·폭 약 150cm(바퀴 바깥)·짐칸 높이 50cm, 26인치(66cm) 자전거형 바퀴", ["#4E5A4A", "#9A7448", "#2A2A2A", "#8E4B2A"],
  "칠이 벗겨진 녹 슨 틀, 바닥 판자 하나 깨짐, 왼쪽 바퀴가 살짝 휘어 반 박자 늦게 덜컹",
  "두 바퀴 손수레. 앞에 가로 손잡이 막대, 둘레에 낮은 쇠 난간, 바닥은 나무 판자",
  "만석의 일과 소리 '끼익, 덜컹'(왼쪽 바퀴가 반 박자 늦다). 손잡이를 쥔 손 = 만석의 감정(2-10·3-26 매치 컷)",
  ("an old two-wheeled Korean handcart (rear-car)", "a pipe-frame cart with a horizontal pull bar at the front, low iron side rails, a wooden plank bed, two rubber-tired wheels",
   "steel pipe, wooden planks, rubber tires", "about 200cm long and 150cm wide, 26-inch (66cm) bicycle-type wheels", "flaking paint and rust, one cracked plank, the left wheel slightly warped"),
  notes="크기는 현재 기준(고증 일부 확인), 색은 미확인"),
"blanket": X(
  "목화솜 이불(홑청 씌움)",
  "150×200cm, 두께 6cm", ["#C9636A", "#F1E6D2", "#7A8A5A"],
  "빨아 바랜 홑청, 솜이 뭉친 자리",
  "분홍 바탕 큰 꽃무늬 홑청 이불. 은주·동민이 둘둘 말아 기어 다님",
  "동민이 이불째 데굴데굴(1-5), 은주가 귀까지 끌어올림(2-25·2-29)",
  ("a padded cotton quilt", "a thick quilt with a pink cover printed with large flowers", "cotton cover, cotton batting", "150 by 200cm, 6cm thick", "faded from washing, lumpy batting"),
  notes="대본대로 이불(목화솜). 1970~80년대 밍크담요 유행 자료(홍보성 매체, 검색 요약)가 있어 밍크담요로 바꿔도 됨 — 선택지(props.md 디자인 판단)"),
"plywood_wall": X(
  "얇은 합판 칸막이 벽(각목 틀)",
  "높이 200cm, 두께 1cm 합판, 각목 4×4cm", ["#B8956A", "#8A6A45", "#E3D5B8"],
  "합판 이음매가 벌어지고 결이 들뜸, 은주가 두드리는 자리만 손때로 짙음, 신문지 도배 조각",
  "판잣집 두 칸을 나누는 얇은 합판 한 장 벽. 단면으로 보면 양쪽에 은주와 동민",
  "엄마의 '톡톡 = 괜찮아'가 오가는 벽(1-5·2-25·3-19)",
  ("a thin plywood partition wall", "a single sheet of thin plywood on a frame of square wooden studs, pieces of old newspaper pasted on as wallpaper, one patch darker from knuckles",
   "plywood, wooden studs", "200cm high, 1cm thick", "gaping seams, lifting wood grain")),
"bulb": X(
  "60W 백열전구(맑은 유리), 소켓, 전깃줄",
  "전구 길이 10cm·지름 6cm, 줄 길이 50cm", ["#F5D27A", "#2A2A2A", "#E8E2D6"],
  "필라멘트가 보이는 맑은 유리, 소켓에 그을음",
  "천장에서 검은 줄로 늘어진 소켓 하나에 백열전구. 공부방은 세 개, 천막은 기둥에 매단 것",
  "가난한 빛. 판잣집·공방·공부방·천막의 노란 빛, 흔들림(2-2)",
  ("a bare 60W incandescent light bulb hanging on a cord", "a clear glass bulb with a visible filament in a black socket hanging from a twisted cord", "glass, bakelite socket, cord", "bulb 10cm long", "soot on the socket")),
"sheet_music": X(
  "인쇄 악보와 손으로 적은 오선지 몇 장",
  "장당 25.7×36.4cm", ["#F2EEE4", "#2B2B2B", "#C9C2B0"],
  "귀퉁이가 말리고 접힌 자국",
  "낱장 악보. 오선과 음표 덩어리(읽을 수 없는 표시)",
  "빈 케이스 속 물건(1-6 쏟아짐), 전당표를 끼우는 곳(2-8)",
  ("a few sheets of printed sheet music", "loose sheets with staff lines and dense note marks that are not readable", "paper", "25.7 by 36.4cm", "curled corners, fold creases")),
"candy": X(
  "알사탕(투명 셀로판 비틀어 포장)",
  "알 지름 2cm, 포장 포함 5cm", ["#E8564A", "#F2C94C", "#5AA0D8", "#7FB77E"],
  "새것",
  "둥근 알사탕을 셀로판으로 싸 양 끝을 비튼 것, 빨강·노랑·파랑·초록",
  "선영의 사탕 — 아이들을 모으는 미끼(1-6 쏟아짐, 1-8 나눔)",
  ("colorful wrapped hard candies", "round hard candies each wrapped in clear cellophane twisted at both ends, red, yellow, blue and green", "sugar candy, cellophane", "candy 2cm, 5cm wrapped", "new and shiny"),
  notes="1980년대 사탕 포장은 미확인 — 셀로판 비틀기 포장은 추측"),
"bus_token": X(
  "황동 버스 토큰(일반용)",
  "지름 1.8cm, 가운데 둥근 구멍", ["#C9A24A", "#8A7A50"],
  "손때로 반질",
  "가운데 둥근 구멍이 뚫린 누런 황동 원판, 무늬 없음",
  "선영의 가난 — 사탕은 버려도 토큰은 필사적으로 주움(1-6), 몇 번이나 셈(2-3)",
  ("a brass city bus token", "a small plain brass disc with a round hole in the center", "brass", "1.8cm across", "worn shiny by handling")),
"nurungji": X(
  "누룽지(국밥집 가마솥 바닥에서 긁어 낸 것)",
  "손바닥만 한 조각 10×7cm, 두께 0.6cm", ["#D9A85A", "#B07A3A", "#F0D9A8"],
  "가장자리가 노릇하게 탐, 부스러기",
  "납작하고 울퉁불퉁한 누룽지 판, 밥알 결이 보임",
  "덕수의 간식, 와삭. 첫 소리에 떨어뜨림(1-11 무음), 누운 입에 그대로(2-1)",
  ("a piece of scorched rice crust", "a flat irregular slab of crispy toasted rice with grains visible", "toasted rice", "10 by 7cm", "browned edges, crumbs")),
"pyeongsang": X(
  "나무 평상(각목 다리, 널판 상판)",
  "180×120cm, 높이 45cm", ["#A8845A", "#7A5A3A", "#D8C29A"],
  "널판 사이 틈, 국물 얼룩, 모서리 닳음",
  "낮고 넓은 나무 마루 평상, 널판을 나란히 박음",
  "천막의 자리. 아저씨들 국밥, 아이들이 평상을 두드리며 웃음(2-1), 접힌 신문(2-20)",
  ("a low wooden platform bench (pyeongsang)", "a wide low platform of parallel wooden planks on square legs", "wood", "180 by 120cm, 45cm high", "gaps between planks, soup stains, worn corners")),
"sandpaper": X(
  "사포(종이 사포)",
  "23×28cm 한 장을 4등분해 손에 쥠(11×14cm)", ["#B5875A", "#8A6A45"],
  "많이 써서 가운데가 닳아 매끈, 접혀 쥔 자국",
  "모래가 붙은 뒷면 종이, 접어 손에 쥠",
  "곽 영감의 생각하는 손. 웃음 사이로 사포질이 멈춤(1-8), 느려짐(1-9), 은주가 동그리를 내리자 멎음(2-22)",
  ("a folded sheet of sandpaper", "a quarter sheet of sandpaper folded over in a hand", "abrasive paper", "11 by 14cm", "worn smooth in the middle")),
"soup_tent": X(
  "바랜 캔버스 천막에 파랑·흰 줄무늬 방수포 조각을 덧댐, 나무 기둥",
  "폭 600cm·깊이 400cm·높이 250cm, 기둥 지름 10cm", ["#C8A574", "#8A6A45", "#3E6E9E", "#E8E2D6"],
  "덧댄 천 조각들이 색이 다름, 빗물 얼룩, 자락이 바람에 들썩",
  "기둥 몇 개에 친 사각 천막, 앞 자락을 걷어 올림, 기둥에 전구와 달력",
  "섬의 거실·첫 연습실·주민 회의장",
  ("a patched canvas tent eating place", "a rectangular faded canvas tent on wooden poles with the front flap rolled up, patches of blue-and-white striped tarpaulin sewn on, a bulb hanging from a pole", "canvas, wooden poles",
   "6m wide, 4m deep, 2.5m high", "rain stains, patches of blue-and-white striped tarpaulin sewn on"),
  notes="주황 비닐 천막은 1987 근거 없음(고증) — 바랜 캔버스와 줄무늬 방수포"),
"tin_roof": X(
  "골함석 지붕(아연도금 강판)",
  "골 간격 7.6cm, 장당 80×180cm", ["#9DA3A6", "#8E4B2A", "#6E7276"],
  "녹 줄이 골을 따라 흐름, 판 겹친 자리 들뜸 — 바람에 덜컹",
  "물결 모양 골함석 여러 장을 겹쳐 덮은 지붕, 위에 돌 몇 개",
  "고물상의 소리(바람에 덜컹), 밤의 불빛이 새는 틈(1-10)",
  ("a corrugated iron roof", "overlapping sheets of corrugated galvanized iron weighed down with a few stones", "galvanized steel", "corrugation pitch 7.6cm, sheets 80 by 180cm", "rust streaks along the ridges, lifted overlaps")),
"notice_board": X(
  "섬 어귀 나무 게시판(기둥 2개, 합판 판)",
  "판 120×90cm, 기둥 높이 180cm", ["#8A6A45", "#C8B28A", "#5A4A3A"],
  "비바람에 바래 회갈색, 옛 압정 구멍과 찢긴 종이 조각",
  "두 기둥 사이 합판 한 장, 위에 좁은 지붕 판",
  "두 장의 종이(꿈과 철거)가 나란히 붙는 곳(1-15~17), 빨간 도장 둘(2-15)",
  ("a weathered plywood notice board on two posts", "a plywood panel between two wooden posts with a narrow little roof board on top, old pin holes and scraps of torn paper", "plywood, wood",
   "panel 120 by 90cm, posts 180cm tall", "faded gray-brown by weather")),
"thumbtacks": X(
  "금속 압정(둥근 머리, 플라스틱 머리 보급 시기는 미확인)",
  "머리 지름 1cm, 침 길이 0.8cm", ["#C9A24A", "#C7CBC9"],
  "새것, 진흙에 떨어진 것 하나",
  "납작한 둥근 금속 머리에 짧은 침. 동민이 든 작은 통",
  "꾹 꾹 꾹 꾹 — 네 귀퉁이(1-15), 최 계장이 진흙에서 주워 닦음(1-16)",
  ("brass thumbtacks", "flat round brass heads with short pins, shown loose and in a small tin box", "brass, steel", "head 1cm across", "new, one tack smeared with mud")),
"choi_envelope": X(
  "누런 서류 봉투(크라프트지, 끈 단추)",
  "33×24cm", ["#C8A66A", "#8A6A40", "#2B2B2B"],
  "모서리 닳음, 입구로 종이가 삐져나옴",
  "직사각 대봉투, 뒷면 덮개에 둥근 단추 두 개와 감는 끈",
  "최 계장의 서류=규정. 옆구리에 끼고 다님, 버스 앞에서 가슴에 안음(3-29)",
  ("a manila document envelope", "a large kraft envelope with a flap closed by a string wound around two round buttons, papers sticking out", "kraft paper", "33 by 24cm", "worn corners")),
"choi_shoes": X(
  "검은 가죽 끈 구두",
  "길이 26.5cm", ["#1E1C1A", "#4A4440", "#8A7258"],
  "반들반들 닦은 구두에 진흙이 달라붙음",
  "앞이 둥근 끈 구두, 굽 낮음",
  "얼굴 대신 보이는 최 계장(1-16 까치발), 뚱보 소리에 멈춘 구두 끝(2-6·회상 3-12·3-20)",
  ("a pair of polished black leather lace-up shoes", "round-toed men's oxford shoes with low heels", "black leather", "26.5cm long", "polished shine with mud sticking to the soles and toes")),
"charter_bus": X(
  "낡은 관광(전세) 버스(리어엔진 각진 차체)",
  "길이 1100cm, 높이 320cm", ["#E8E2D6", "#3E6E8E", "#C0392F", "#5A5E62"],
  "칠이 바래고 범퍼 녹, 털털 쿨럭 엔진",
  "앞이 납작한 1980년대 대형 버스, 옆면 띠 장식, 앞 유리 안쪽에 손글씨 종이(글씨는 식자)",
  "섬사람들을 서울 한복판으로(3-16), 노을 둑길로 돌아옴(3-30)",
  ("an old 1980s Korean chartered coach bus", "a boxy rear-engine coach with a flat front with a painted side stripe, a handwritten paper sign inside the windshield with no readable letters", "steel body",
   "1100cm long", "faded paint, rusty bumper")),
"piano_wire": X(
  "피아노 강선 다발(고음부 맨 강선, 저음부 구리 감은 줄)",
  "가는 줄 굵기 0.8~1mm, 길이 50~150cm, 다발 지름 30cm로 감음", ["#C7CBC9", "#B5653A", "#8E9396"],
  "부서진 피아노에서 떼어 냄, 끝이 꼬불",
  "둥글게 감아 묶은 쇠줄 다발, 굵은 구리 감은 줄 몇 가닥",
  "'이거 한 대면 일 년은 간다'(2-1) — 뚱보의 새 줄, 2·3호의 줄(3-9)",
  ("a coiled bundle of piano strings", "a loose coil of shiny steel piano wires with a few thick copper-wound bass strings, tied with wire", "steel, copper", "coil 30cm across", "kinked curly ends")),
"taejun_case": X(
  "고급 바이올린 케이스(가죽 커버, 금속 잠금쇠)",
  "길이 80cm, 폭 26cm, 두께 12cm", ["#3A2A22", "#C9A24A", "#2A3A5A"],
  "흠 없이 반짝, 잠금쇠 하나가 헛돎(2-4 딸깍)",
  "사각에 가까운 직사각 고급 케이스, 반짝이는 금색 잠금쇠 2, 손잡이. 안은 남색 벨벳",
  "태준의 세계. 손끝이 떨려 잠금쇠가 헛돎(2-4), 여분 E현을 꺼냄(3-22)",
  ("an expensive oblong violin case", "an oblong hard case covered in dark brown leather with two shiny gold latches and a handle, open showing navy velvet lining", "leather, brass, velvet",
   "80cm long, 26cm wide", "flawless and polished")),
"olympic_poster": X(
  "올림픽 표어 포스터(종이 인쇄, 표어만 — 식자 문구 예: '선진국 시민답게, 올림픽 주인답게')",
  "54×78cm", ["#F2EEE4", "#2E5AA0", "#C0392F", "#F2C94C"],
  "벽에 붙어 귀퉁이 들뜸",
  "흰 바탕에 굵은 표어 줄(글자는 식자)과 오색 띠 장식. 마스코트·엠블럼 없음",
  "시대(올림픽 2달 전)의 압력, 연습실 벽(2-4)·구청 벽(3-12)",
  ("a 1988 civic campaign slogan poster", "a white poster with bold blank slogan bars and simple colored stripe decoration, no mascot, no emblem, no rings", "printed paper", "54 by 78cm", "corners lifting from the wall"),
  notes="올림픽 공식 마스코트·엠블럼·오륜 금지"),
"ballpoint_pen": X(
  "흰 육각 몸통 노크식 볼펜(캡 없음)",
  "길이 14cm(미확인)", ["#F2F0EA", "#1E1E1E", "#A7ACB0"],
  "몸통 끝을 씹은 자국",
  "흰 육각 플라스틱 몸통, 위에 검은 노크 버튼, 아래 금속 팁. 캡 없음",
  "최 계장의 기록 '특이 사항 없음'(2-7), 꾹꾹 누른 보고서(3-12)",
  ("a plain click ballpoint pen", "a white hexagonal plastic barrel with a black click button on top and a metal tip, no cap", "plastic, metal tip", "14cm long", "chewed end"),
  notes="흔한 국산 볼펜 모양을 따르되 상표 없음"),
"door_bell": X(
  "문 위의 놋쇠 종(용수철 고리)",
  "종 지름 6cm", ["#C9A24A", "#8A6A30"],
  "누렇게 변색",
  "문틀 위 용수철 쇠에 매단 작은 종",
  "딸랑 — 전당포를 드나드는 박자(2-8·3-33)",
  ("a small brass shop door bell", "a little bell hung on a curled spring bracket above a door", "brass, steel spring", "6cm across", "tarnished")),
"abacus": X(
  "나무 주판(검은 알)",
  "길이 33cm, 폭 7cm, 23줄", ["#5A3A24", "#1E1E1E", "#D8C29A"],
  "알이 반질, 틀 모서리 닳음",
  "나무 틀에 가로 칸막이, 위 1알·아래 4알",
  "전당포 주인의 무덤덤함(2-8 타닥 타닥)",
  ("a wooden abacus", "a wooden frame with a horizontal divider, one bead above and four below on each rod", "wood", "33 by 7cm", "beads polished by use")),
"flashlight": X(
  "원통형 백열 손전등(D형 건전지 2개)",
  "길이 20cm, 머리 지름 6cm", ["#4E5A4A", "#C7CBC9", "#F5D27A"],
  "칠 벗겨짐, 전구 반사경 흐림",
  "원통 몸통에 넓은 머리, 옆 밀이 스위치, 끝에 거는 고리",
  "밤의 불빛 둘(2-11·2-12 미자와 곽 영감), 만석이 산을 오름(2-26·2-27·3-25)",
  ("an old cylindrical flashlight", "a tube body for two D-cell batteries with a wider head, an incandescent bulb behind a dull reflector giving a warm yellow beam, a slide switch on the side and a hanging loop at the tail", "metal or plastic", "20cm long", "chipped finish, dull reflector")),
"apple_crate": X(
  "나무 사과 궤짝(얇은 판자, 틈 있음)",
  "45×30×30cm", ["#C8A574", "#8A6A45", "#5A4A3A"],
  "판자 틈 사이로 짚 부스러기, 모서리 못이 녹슴",
  "얇은 판자를 틈을 두고 박은 직사각 상자, 양 끝 판에 손잡이 구멍",
  "만석이 사흘 밤 앉아 있던 자리(2-28 발끝으로 밀어 놓음 → 3-1 '사흘 밤을 저기' → 3-10 다시 앉음)",
  ("an empty wooden apple crate", "a slatted crate of thin boards with gaps, hand holes in the end boards", "thin pine boards, nails", "45 by 30 by 30cm", "rusty nail heads, bits of straw")),
"composition_notebook": X(
  "얇은 공책(종이 표지)",
  "18×25cm, 30쪽", ["#E8DCC0", "#5E7F99", "#2B2B2B"],
  "표지 귀퉁이 말림, 연필 글씨(식자 단계)",
  "가로줄 공책, 단색 표지",
  "은주의 첫 작곡 '새벽. 트럭. 낮은 솔. 기침.'(3-4)",
  ("a thin school notebook", "a lined exercise notebook with a plain blue-gray paper cover, a few pencil scribbles that are not readable", "paper", "18 by 25cm", "curled cover corner")),
"staff_paper": X(
  "오선지 낱장",
  "25.7×36.4cm, 12단", ["#F4F0E6", "#2B2B2B", "#9A968C"],
  "연필 자국·지운 흔적, 칸 나눔 선",
  "가로 오선 12단 인쇄 종이, 연필로 칸을 나누고 표시(글씨는 식자)",
  "「섬의 하루」가 생기는 종이(3-5 새벽 → 3-6 저녁 빈칸 → 3-8 '독주' → 3-10 제목)",
  ("manuscript staff paper with pencil marks", "a sheet printed with twelve staves, pencil lines dividing it into sections, scribbled note marks that are not readable", "paper", "25.7 by 36.4cm", "eraser smudges")),
"kwak_pencil": X(
  "목수 연필(납작한 몸통, 1980년대 국내 보급은 미확인)",
  "길이 17cm, 단면 1.2×0.6cm", ["#C0392F", "#E3C79A", "#2B2B2B"],
  "칼로 깎은 뭉툭한 심",
  "납작한 직사각 단면 연필, 귀에 꽂음",
  "곽 영감의 표식(귀에 연필) — 15년 뒤에도(3-34)",
  ("a flat carpenter's pencil", "a flat rectangular-section pencil sharpened with a knife", "wood, graphite", "17cm long", "blunt knife-cut point")),
"pencil": X(
  "육각 나무 연필",
  "길이 15cm(깎아 짧아짐)", ["#F2C94C", "#E3C79A", "#2B2B2B"],
  "끝에 지우개 없음, 씹은 자국",
  "노란 칠 육각 연필",
  "은주가 소리를 적고, 선영이 떨어뜨림(3-5 또르르)",
  ("a plain hexagonal pencil", "a yellow-painted hexagonal wooden pencil", "wood, graphite", "15cm long", "worn and shortened, bite marks")),
"glasses_seonyoung": X(
  "크고 동그란 가는 금테 안경",
  "알 지름 5cm, 전체 폭 14cm", ["#C9A24A", "#E8EEF2"],
  "자꾸 흘러내림, 코받침 헐거움",
  "큰 원형 렌즈 두 개, 가는 금속테",
  "선영의 긴장 신호(고쳐 씀), 김이 서림(3-27)",
  ("large round thin gold-rim glasses", "two big round lenses in a thin gold metal frame", "metal, glass", "lenses 5cm across", "slightly loose nose pads")),
"glasses_choi": X(
  "두꺼운 검은 뿔테 안경",
  "알 가로 5cm, 전체 폭 14.5cm", ["#1E1C1A", "#E8EEF2"],
  "땀에 미끄러짐",
  "두껍고 각진 검은 테",
  "최 계장 얼굴의 고정 요소",
  ("thick black horn-rimmed glasses", "heavy squarish black frames", "plastic, glass", "frame 14.5cm wide", "a smear of sweat on the lens")),
"reading_glasses_kwak": X(
  "돋보기안경(쇠테, 반달 렌즈)",
  "알 가로 4.5cm, 전체 폭 13.5cm", ["#8E9396", "#E8EEF2"],
  "늘 이마에 올려 둠, 테 한쪽이 살짝 휨",
  "얇은 쇠테 둥근 돋보기",
  "이마 → 눈으로 내려 씀(1-3), 웃음에 콧등으로 미끄러짐(3-15)",
  ("old wire-rim reading glasses", "thin round steel-rim reading glasses", "steel, glass", "13.5cm wide", "one temple slightly bent")),
"work_cap_manseok": X(
  "국방색 면 작업모(챙 있는 모자) — 형태 미확인",
  "머리둘레 57cm, 챙 6cm", ["#5B6145", "#3E4230", "#8A8A70"],
  "챙 끝이 해져 올 풀림, 땀 자국",
  "둥근 윗부분, 앞챙이 짧은 작업모",
  "만석의 얼굴을 그늘지게 하는 모자(character 고정 문구)",
  ("a worn olive work cap", "a soft round cotton cap with a short front brim", "olive cotton", "brim 6cm", "frayed brim edge, sweat stains")),
"bandage": X(
  "일회용 반창고(살색 띠)",
  "7×2cm", ["#E0B48A", "#C8996A"],
  "가장자리 때 묻어 들뜸",
  "가운데 패드가 있는 작은 띠 반창고. 미자 코 위 가로, 동민 오른쪽 무릎",
  "미자·동민의 고정 표식",
  ("a small adhesive bandage strip", "a skin-colored strip bandage with a center pad", "fabric tape", "7 by 2cm", "grubby edges lifting")),
"hair_tie": X(
  "고무줄(가는 노란 고무줄 여러 번 감음) — 고증 미확인",
  "지름 3cm", ["#D9A441", "#8A6A30"],
  "늘어나 헐거움",
  "가는 고무줄을 몇 번 감아 목덜미 아래로 머리를 낮게 묶음",
  "은주의 고정 머리. 2-25 소리굽쇠 사슬에 걸려 풀리며 머리가 흘러내림, 15년 뒤에도 고무줄 하나(3-34)",
  ("a plain rubber band hair tie", "a thin rubber band wound a few times", "rubber", "3cm across", "stretched loose")),
"stage_curtain": X(
  "붉은 벨벳 무대 막",
  "높이 7m, 주름 간격 30cm", ["#8E1E24", "#5A1418", "#C9A24A"],
  "아래 단 먼지, 무대 옆 그늘",
  "세로 주름이 깊은 두꺼운 붉은 벨벳 막, 아래 금색 술 단",
  "무대 옆 어둠(태준이 기다림, 줄 교체 3-22·3-24), 커튼 그늘의 곽 영감 엄지(3-27)",
  ("a red velvet stage curtain", "a heavy red velvet curtain with deep vertical folds and a gold fringe at the bottom", "velvet", "7m high", "dust along the hem")),
"workshop_cans": X(
  "공방 선반의 빈 깡통들(크기 여러 가지)",
  "지름 7~15cm, 높이 10~20cm", ["#B9BDBF", "#8E4B2A", "#9A7448"],
  "상표 벗겨지고 녹 점",
  "나무 선반에 줄지어 놓인 깡통들",
  "공방의 소리 재료. 곽 영감 웃음에 달그락(3-15)",
  ("a shelf of assorted empty tin cans", "unlabeled tin cans of various sizes lined up on a wooden shelf", "tinplate, wood", "cans 7 to 15cm across", "labels removed, rust dots")),
"folding_chair": X(
  "접이식 철제 의자(나무 또는 철판 좌판)",
  "높이 80cm, 좌판 40×40cm", ["#6E7276", "#3A3A3A", "#9A7448"],
  "칠이 벗겨짐",
  "X자로 접히는 철 다리, 납작한 좌판과 등판",
  "무대 옆 곽 영감의 조율 자리(3-18), 2003 객석과 라디오 의자(3-34)",
  ("a metal folding chair", "a folding chair with crossing steel legs, a flat seat and backrest", "steel", "80cm high", "chipped paint")),
"flat_board": X(
  "넓적한 판자 조각",
  "60×30cm, 두께 2cm", ["#9A7A58", "#6E5A40"],
  "비바람에 회갈색, 한쪽 모서리 깨짐",
  "작은 산 꼭대기에 놓인 납작한 판자",
  "동그리가 처음 소리를 낸 자리이자 버려지는 자리(2-23), 만석이 찾는 자리(2-27)",
  ("a flat weathered wooden board", "a flat plank lying on trash", "wood", "60 by 30cm", "grayed by weather, one broken corner")),
"white_vinyl": X(
  "흰 비닐 조각(쓰레기 산)",
  "30~100cm 조각", ["#F2F0EA", "#C8C4BA", "#9A9690"],
  "찢어지고 흙이 묻음",
  "바람에 펄럭이는 찢어진 흰 비닐 시트",
  "쓰레기 산의 바람 소리. 첫 소리에 내려앉음(1-11), 미자가 흔드는 '내 구역 바람'(3-6), 본선 '한낮'(3-20)",
  ("torn white plastic sheets blowing in the wind", "ragged pieces of thin white plastic film flapping", "plastic film", "30 to 100cm pieces", "torn and smudged with soil")),
"gukbap": X(
  "국밥(흑갈색 뚝배기)",
  "뚝배기 지름 15cm, 높이 8cm", ["#3A2A22", "#E8DCC0", "#C0392F"],
  "김이 오름",
  "검은 뚝배기에 뽀얀 국물과 밥, 숟가락",
  "손대지 않은 국밥(2-21 김이 사라질 때까지)",
  ("a bowl of Korean rice soup", "a dark earthenware bowl of milky broth with rice, steam rising, a spoon beside it", "earthenware", "bowl 15cm across", "hot and steaming")),
"shack_door": X(
  "판잣집 합판 문과 쇠 문고리",
  "문 170×70cm, 문고리 지름 5cm", ["#8A6A45", "#5A5E62", "#C8B28A"],
  "문틀이 비틀려 틈, 문고리 녹",
  "합판 문에 둥근 쇠고리 손잡이, 문 옆 못(손전등 걸이)",
  "만석의 목수건이 걸리는 자리(1-4), 쪽방 문고리 위의 손(2-26)",
  ("a plywood shack door with an iron ring handle", "a plain plywood door in a warped frame, a round iron ring handle, a nail beside it", "plywood, iron", "170 by 70cm", "rusty ring, gaps at the frame")),
"eunju_navy_jumper": X(
  "남색 나일론 점퍼(오빠 것 같은 큰 치수)",
  "기장 70cm(은주 엉덩이 아래까지), 소매가 손등을 덮음", ["#2E3A5C", "#1E2840", "#5A5048"],
  "팔꿈치 반질, 소매 끝 해짐",
  "지퍼 점퍼, 큰 주머니 둘, 넉넉한 품",
  "은주의 기본 의상(목장갑을 주머니에, 돈을 안주머니에)",
  ("an oversized navy nylon zip jacket", "a loose zip-up jacket with two big pockets, sleeves covering the hands", "nylon", "70cm long", "shiny worn elbows, frayed cuffs"),
  notes="characters.json 의상 색 #2E3A5C"),
"eunju_school_blouse": X(
  "빛바랜 흰 블라우스·감색 치마",
  "블라우스 기장 55cm, 치마 무릎길이", ["#F1EEE6", "#2E3A5C", "#D8D4C8"],
  "흰빛이 누렇게 바램",
  "둥근 깃 흰 블라우스(깃 모양 미확인), 주름 감색 치마",
  "예선 날 '제일 좋은 옷' — 사슬만 보이고 소리굽쇠는 안에(2-18)",
  ("a faded white blouse and navy skirt", "a white short-sleeved blouse with a small collar and a pleated navy knee-length skirt", "cotton", "girl's size", "the white yellowed with age")),
"borrowed_white_dress": X(
  "선영이 빌려 온 흰 원피스(무대)",
  "기장 95cm(무릎 아래), 은주에게 커서 소매가 손등 반을 덮음", ["#FAFAF7", "#E6E2D8"],
  "다린 주름, 커서 헐렁",
  "둥근 깃 흰 원피스, 긴 소매, 허리 리본",
  "본선 무대 옷. 소매를 걷어도 흘러내림(3-17), 뛰면 자락이 날림(3-21)",
  ("a borrowed white dress", "a plain white dress with a round collar, long sleeves and a waist ribbon, hanging on a nail", "cotton", "below-knee length", "ironed creases, too big for a small girl")),
"manseok_field_jacket": X(
  "국방색 민무늬 야전상의(낡음)",
  "기장 80cm", ["#5B6145", "#3E4230", "#8A8A70"],
  "쇳가루 얼룩, 소매 해짐, 단추 하나 다른 것",
  "무늬 없는 국방색 군용 야전상의, 가슴 주머니 둘·허리 주머니 둘, 깃",
  "만석의 등과 품. 전당표를 넣는 안주머니, 동그리를 품는 단추(2-27)",
  ("a worn plain olive drab military field jacket", "a plain olive field jacket with no camouflage pattern, two chest and two hip pockets, a collar, button front", "cotton twill", "80cm long",
   "iron-dust stains, frayed cuffs, one mismatched button"),
  notes="얼룩무늬는 1990년 이후라 쓰지 않음(고증)"),
"kwak_apron": X(
  "톱밥 묻은 캔버스 앞치마·팔토시",
  "앞치마 길이 90cm, 토시 길이 30cm", ["#8A7556", "#5A4A30", "#2A2A2A"],
  "톱밥·아교·기름 얼룩",
  "목에 거는 캔버스 앞치마(가슴 주머니에 연필·자), 양팔에 검은 토시",
  "곽 영감의 작업복. 웃다 앞치마로 눈가를 훔침(3-15)",
  ("a canvas work apron and black sleeve covers", "a bib apron of heavy canvas with a chest pocket, a pair of black cotton sleeve protectors", "canvas, cotton", "apron 90cm long", "sawdust, glue and oil stains")),
"sunrye_apron": X(
  "꽃무늬 앞치마(나일론) + 몸뻬",
  "앞치마 길이 70cm", ["#B5546A", "#F2E6D8", "#5B4E6A"],
  "국물 얼룩, 빨아 바램",
  "허리에 두르는 꽃무늬 앞치마, 아래 고무줄 몸뻬 바지",
  "순례 할머니의 표식. 본선 날 곱게 접어 손에(3-16), 15년 뒤 덕수가 두름(3-34)",
  ("a floral print apron with momppe pants", "a waist apron with a flower print over loose elastic-waist work pants gathered at the ankles", "nylon", "apron 70cm long", "soup stains, faded"),
  notes="몸뻬는 고증 확인, 앞치마 무늬는 미확인"),
"mija_red_tracksuit": X(
  "빨간 트레이닝(저지) 상의",
  "기장 60cm", ["#C0392F", "#8E2A22", "#33363E"],
  "무릎·팔꿈치 보풀, 소매 끝 늘어남",
  "지퍼 앞여밈 저지 상의, 목까지 올라오는 깃",
  "미자의 빨강 — 무채색 쓰레기 산의 원색 점",
  ("a red zip-up track jacket", "a jersey track jacket with a stand collar and front zipper", "polyester jersey", "60cm long", "pilling at the elbows, stretched cuffs")),
"deoksu_check_shirt": X(
  "체크 남방(늘어난 흰 러닝셔츠 위)",
  "기장 65cm(남자아이 큰 치수)", ["#5D7DA8", "#F2F0EA", "#2E3A5C"],
  "단추가 한 칸씩 어긋남, 주머니에 누룽지 부스러기",
  "파랑 체크 반팔/긴팔 남방, 가슴 주머니",
  "덕수의 고정 의상. 예선·본선엔 단추를 목까지 잠금",
  ("a blue plaid button shirt", "a blue plaid shirt with a chest pocket, buttons done up one hole off", "cotton", "boy's large size", "crumbs in the pocket")),
"dongmin_tracksuit": X(
  "물려받은 큰 초록 운동복",
  "상의 기장 55cm, 바지 길이 85cm(밑단을 두 번 접음)", ["#3F7A55", "#2A5A3E", "#F2F0EA"],
  "무릎 해짐, 소매가 손등 덮음",
  "지퍼 없는 초록 운동복 위아래",
  "형이 물려준 옷(바이블)",
  ("an oversized hand-me-down green tracksuit", "a pull-over green sweat top and pants, cuffs rolled twice", "cotton jersey", "child size, too big", "worn knees")),
"taejun_uniform": X(
  "사립중학교 교복(감색 재킷·넥타이)",
  "남자 중학생 165cm 치수", ["#1F2A4A", "#2A2E38", "#F2F0EA", "#8E1E24"],
  "다림질 자국 반듯",
  "감색 싱글 재킷, 흰 셔츠, 넥타이, 회색빛 바지",
  "다솜중의 반듯함(2-4·2-18 객석)",
  ("a private middle school uniform", "a navy single-breasted blazer, white shirt, dark tie and dark trousers", "wool blend", "boy's size", "crisply pressed"),
  notes="1987~88 교복 학교는 소수(1989년 약 13%). 사립중 설정으로 둠 — 시대 착오 의심 목록에 기록"),
"concert_black": X(
  "검은 연주복(다솜중 단원·선영)",
  "남자 재킷 기장 70cm, 여자 드레스 기장 120cm", ["#18181C", "#2A2A30", "#F2F0EA"],
  "반듯",
  "남자: 검은 재킷·흰 셔츠·검은 나비넥타이 또는 넥타이 / 여자: 검은 긴 드레스",
  "본선의 검정 줄 vs 섬 아이들의 빨간 손수건(3-27)",
  ("black concert clothes", "a black jacket with white shirt for boys and a long black dress for women, shown side by side", "black wool and polyester", "adult and teen sizes", "neat and pressed")),
"choi_gray_suit": X(
  "회색 기성복 양복·넥타이",
  "168cm 중년 남자 치수", ["#7A7C80", "#6A6C70", "#8E2A22", "#F2F0EA"],
  "땀에 겨드랑이 짙음, 바지 무릎 늘어남",
  "회색 싱글 양복, 흰 셔츠, 무늬 넥타이",
  "최 계장의 '규정'",
  ("a gray off-the-rack business suit", "a gray single-breasted suit with white shirt and a patterned tie", "wool blend", "middle-aged man's size", "sweat marks under the arms, baggy knees")),
"seonyoung_outfit": X(
  "구겨진 흰 셔츠·낡은 카디건·긴 플레어스커트",
  "스커트 길이 85cm(발목 위)", ["#F2EFE8", "#B8A68A", "#5E6A7A"],
  "셔츠 구김, 카디건 보풀",
  "흰 셔츠 위 베이지 카디건, 회청색 긴 플레어스커트",
  "선영의 기본 의상",
  ("a rumpled white shirt, old cardigan and long flared skirt", "a white blouse under a beige cardigan and an ankle-length gray-blue flared skirt", "cotton, wool", "women's size", "wrinkled shirt, pilled cardigan")),
}
